"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";

type Evidence = { source: { sourceId: string; sourceType: string; title: string; observedAt?: string | null; market?: string | null; locale?: string | null }; claims: Array<{ claimId: string; statement: string; confidence?: number | null }> };
type Hypothesis = { id: string; statement: string; targetSegment: string; targetMetric: string; expectedDirection: string; evidenceSufficiency: string; riskClass: string; status: string; tenantId: string; guildId?: string | null; characterId?: string | null; market?: string | null; country?: string | null; locale?: string | null };
type Proposal = { id: string; hypothesisId: string; proposedAction: string; expectedImpact: string; targetMetric: string; expectedDirection: string; reversible: boolean; implementationEffort: string; evidenceSufficiency: string; riskClass: string; approvalRequired: boolean; approvalStatus: string; decision: string; missingEvidence: Array<{ type: string; reason: string }>; status: string; tenantId: string; guildId?: string | null; characterId?: string | null; market?: string | null; country?: string | null; locale?: string | null };
type HypothesisDetail = { hypothesis: Hypothesis; evidenceLinks: Array<{ sourceId: string; claimId?: string | null }>; evidence: Evidence[] };

const blankHypothesis = { statement: "", targetSegment: "", targetMetric: "views", expectedDirection: "INCREASE", characterId: "raven-blackwood", guildId: "raven-guild", market: "JP", country: "JP", locale: "ja-JP" };
const blankProposal = { hypothesisId: "", proposedAction: "", expectedImpact: "", targetMetric: "views", expectedDirection: "INCREASE", reversible: true, implementationEffort: "LOW", riskClass: "LOW", guildId: "raven-guild", market: "JP", country: "JP", locale: "ja-JP" };

export default function GrowthIntelligencePage() {
  const [hypotheses, setHypotheses] = useState<HypothesisDetail[]>([]);
  const [proposals, setProposals] = useState<Proposal[]>([]);
  const [selectedHypothesis, setSelectedHypothesis] = useState<HypothesisDetail | null>(null);
  const [selectedProposal, setSelectedProposal] = useState<Proposal | null>(null);
  const [hypothesisForm, setHypothesisForm] = useState(blankHypothesis);
  const [proposalForm, setProposalForm] = useState(blankProposal);
  const [status, setStatus] = useState("読み込み中...");
  const [busy, setBusy] = useState(false);

  async function read(response: Response) { const payload = await response.json().catch(() => ({})); if (!response.ok || !payload.ok) throw new Error(payload.error || "Growth Intelligenceの操作に失敗しました。"); return payload; }
  async function load() { try { const payload = await read(await fetch("/api/growth-intelligence?tenantId=raven-oracle&guildId=raven-guild&market=JP&country=JP&locale=ja-JP", { cache: "no-store" })); setHypotheses(payload.hypotheses || []); setProposals(payload.proposals || []); setStatus("最新状態を読み込みました。"); } catch (error) { setStatus(error instanceof Error ? error.message : "読み込みに失敗しました。"); } }
  // The initial load intentionally runs once for the fixed admin scope.
  // eslint-disable-next-line react-hooks/exhaustive-deps
  useEffect(() => { queueMicrotask(() => { void load(); }); }, []);
  const proposalHypotheses = useMemo(() => hypotheses.map((item) => item.hypothesis), [hypotheses]);
  async function post(body: Record<string, unknown>, message: string) { setBusy(true); setStatus("処理中..."); try { await read(await fetch("/api/growth-intelligence", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ tenantId: "raven-oracle", ...body }) })); setStatus(message); await load(); } catch (error) { setStatus(error instanceof Error ? error.message : "操作に失敗しました。"); } finally { setBusy(false); } }
  function updateHypothesis(key: string, value: string) { setHypothesisForm((current) => ({ ...current, [key]: value })); }
  function updateProposal(key: string, value: string | boolean) { setProposalForm((current) => ({ ...current, [key]: value })); }

  return <main className="min-h-screen bg-[#f5f0e8] px-5 py-8 text-[#20241f]"><div className="mx-auto max-w-7xl">
    <nav className="flex flex-wrap justify-between gap-3"><Link className="text-sm font-semibold text-[#596d51]" href="/admin/growth/">Growth Engineへ戻る</Link><Link className="text-sm font-semibold text-[#596d51]" href="/admin/">管理ダッシュボード</Link></nav>
    <header className="mt-5 border-b border-[#d7cabc] pb-6"><p className="text-sm font-semibold uppercase text-[#6c5f3d]">Growth Intelligence / Phase 3 Stage 1</p><h1 className="mt-2 text-4xl font-semibold">Hypothesis &amp; Proposal</h1><p className="mt-3 max-w-4xl leading-7 text-[#5e625c]">Evidenceを根拠として、仮説と改善提案を管理します。AI生成・Experiment作成・自動実行はこの画面では行いません。</p></header>
    <p className="mt-4 rounded border border-[#d7cabc] bg-[#fffaf2] p-3 text-sm font-semibold text-[#596d51]" role="status">{status}</p>
    <section className="mt-6 grid gap-5 xl:grid-cols-2"><Panel title="Hypothesisを作成"><div className="grid gap-3">{input("statement", "仮説", hypothesisForm.statement, (v) => updateHypothesis("statement", v), "例：質問型Hookは完視聴率を高める", true)}{input("targetSegment", "対象セグメント", hypothesisForm.targetSegment, (v) => updateHypothesis("targetSegment", v), "例：恋愛相談の新規訪問者", true)}{input("targetMetric", "対象指標", hypothesisForm.targetMetric, (v) => updateHypothesis("targetMetric", v), "views / completion_rate", true)}<Select label="期待方向" value={hypothesisForm.expectedDirection} options={["INCREASE", "DECREASE", "MAINTAIN"]} onChange={(v) => updateHypothesis("expectedDirection", v)} /><button disabled={busy} className="rounded border border-[#596d51] bg-[#596d51] px-4 py-3 font-semibold text-white disabled:opacity-50" onClick={() => post({ action: "create_hypothesis", ...hypothesisForm }, "Hypothesisを作成しました。")}>Hypothesisを作成</button></div></Panel><Panel title="Proposalを作成"><div className="grid gap-3"><Select label="対象Hypothesis" value={proposalForm.hypothesisId} options={["", ...proposalHypotheses.map((item) => item.id)]} labels={(["", ...proposalHypotheses.map((item) => item.id)]).map((id) => id ? `${id}: ${proposalHypotheses.find((item) => item.id === id)?.statement.slice(0, 40)}` : "選択してください")} onChange={(v) => updateProposal("hypothesisId", v)} />{input("proposedAction", "提案する操作", proposalForm.proposedAction, (v) => updateProposal("proposedAction", v), "例：Hookを質問型へ変更", true)}{input("expectedImpact", "期待する影響", proposalForm.expectedImpact, (v) => updateProposal("expectedImpact", v), "例：完視聴率の改善", true)}{input("targetMetric", "対象指標", proposalForm.targetMetric, (v) => updateProposal("targetMetric", v), "completion_rate", true)}<div className="grid gap-3 sm:grid-cols-2"><Select label="期待方向" value={proposalForm.expectedDirection} options={["INCREASE", "DECREASE", "MAINTAIN"]} onChange={(v) => updateProposal("expectedDirection", v)} /><Select label="実装負荷" value={proposalForm.implementationEffort} options={["LOW", "MEDIUM", "HIGH"]} onChange={(v) => updateProposal("implementationEffort", v)} /></div><label className="flex items-center gap-2 text-sm font-semibold"><input type="checkbox" checked={proposalForm.reversible} onChange={(event) => updateProposal("reversible", event.target.checked)} />可逆な変更</label><Select label="Risk Class" value={proposalForm.riskClass} options={["LOW", "MEDIUM", "HIGH", "CRITICAL"]} onChange={(v) => updateProposal("riskClass", v)} /><button disabled={busy || !proposalForm.hypothesisId} className="rounded border border-[#596d51] bg-[#596d51] px-4 py-3 font-semibold text-white disabled:opacity-50" onClick={() => post({ action: "create_proposal", ...proposalForm }, "Proposalを作成しました。")}>Proposalを作成</button></div></Panel></section>
    <section className="mt-6 grid gap-5 xl:grid-cols-2"><Panel title="Hypothesis一覧">{hypotheses.map((item) => <button key={item.hypothesis.id} className="rounded border border-[#d7cabc] bg-white p-4 text-left" onClick={() => setSelectedHypothesis(item)}><p className="text-xs font-semibold text-[#6c5f3d]">{item.hypothesis.id} / {item.hypothesis.status}</p><p className="mt-1 font-semibold">{item.hypothesis.statement}</p><p className="mt-2 text-sm text-[#5e625c]">{item.hypothesis.targetMetric} / {item.hypothesis.expectedDirection} / Sufficiency: {item.hypothesis.evidenceSufficiency}</p></button>)}{!hypotheses.length && <Empty text="Hypothesisはまだありません。" />}</Panel><Panel title="Proposal一覧">{proposals.map((item) => <button key={item.id} className="rounded border border-[#d7cabc] bg-white p-4 text-left" onClick={() => setSelectedProposal(item)}><p className="text-xs font-semibold text-[#6c5f3d]">{item.id} / {item.status}</p><p className="mt-1 font-semibold">{item.proposedAction}</p><p className="mt-2 text-sm text-[#5e625c]">Sufficiency: {item.evidenceSufficiency} / Decision: {item.decision} / Approval: {item.approvalStatus}</p></button>)}{!proposals.length && <Empty text="Proposalはまだありません。" />}</Panel></section>
    {selectedHypothesis && <Detail title="Hypothesis詳細" onClose={() => setSelectedHypothesis(null)}><Field label="Statement" value={selectedHypothesis.hypothesis.statement} /><Field label="Target" value={`${selectedHypothesis.hypothesis.targetSegment} / ${selectedHypothesis.hypothesis.targetMetric} / ${selectedHypothesis.hypothesis.expectedDirection}`} /><Field label="Evidence Sufficiency" value={selectedHypothesis.hypothesis.evidenceSufficiency} /><Field label="Risk / Status" value={`${selectedHypothesis.hypothesis.riskClass} / ${selectedHypothesis.hypothesis.status}`} /><Field label="Scope" value={scopeText(selectedHypothesis.hypothesis)} /><h3 className="mt-4 font-semibold">Supporting Evidence</h3>{selectedHypothesis.evidence.map((item) => <EvidenceCard key={item.source.sourceId} item={item} />)}{!selectedHypothesis.evidence.length && <Empty text="Supporting Evidenceはありません。" />}</Detail>}
    {selectedProposal && <Detail title="Proposal詳細" onClose={() => setSelectedProposal(null)}><Field label="提案" value={selectedProposal.proposedAction} /><Field label="期待する影響" value={selectedProposal.expectedImpact} /><Field label="Metric / Direction" value={`${selectedProposal.targetMetric} / ${selectedProposal.expectedDirection}`} /><Field label="Reversible / Effort" value={`${selectedProposal.reversible ? "可逆" : "不可逆"} / ${selectedProposal.implementationEffort}`} /><Field label="Evidence Sufficiency" value={selectedProposal.evidenceSufficiency} /><Field label="Risk / Approval / Decision" value={`${selectedProposal.riskClass} / ${selectedProposal.approvalStatus} / ${selectedProposal.decision}`} /><Field label="Scope" value={scopeText(selectedProposal)} /><h3 className="mt-4 font-semibold">Missing Evidence</h3>{selectedProposal.missingEvidence.map((item) => <p key={item.type} className="rounded border border-[#d7cabc] bg-[#fffaf2] p-3 text-sm">{item.type}: {item.reason}</p>)}{!selectedProposal.missingEvidence.length && <Empty text="Missing Evidenceはありません。" />}<div className="mt-4 flex flex-wrap gap-3"><button disabled={busy || !selectedProposal.approvalRequired || selectedProposal.approvalStatus === "APPROVED"} className="rounded border border-[#596d51] bg-[#596d51] px-4 py-2 font-semibold text-white disabled:opacity-50" onClick={() => post({ action: "approve_proposal", proposalId: selectedProposal.id, guildId: selectedProposal.guildId, market: selectedProposal.market, country: selectedProposal.country, locale: selectedProposal.locale }, "Proposalを承認しました。")}>承認</button><button disabled={busy || selectedProposal.status === "REJECTED"} className="rounded border border-[#9a4e43] px-4 py-2 font-semibold text-[#9a4e43] disabled:opacity-50" onClick={() => post({ action: "reject_proposal", proposalId: selectedProposal.id, guildId: selectedProposal.guildId, market: selectedProposal.market, country: selectedProposal.country, locale: selectedProposal.locale }, "Proposalを却下しました。")}>却下</button></div></Detail>}
  </div></main>;
}

function input(name: string, label: string, value: string, onChange: (value: string) => void, placeholder: string, required = false) { return <label className="grid gap-1 text-sm font-semibold" htmlFor={name}>{label}{required ? " *" : ""}<input id={name} className="rounded border border-[#d7cabc] bg-white px-3 py-2 font-normal" value={value} placeholder={placeholder} onChange={(event) => onChange(event.target.value)} /></label>; }
function Select({ label, value, options, labels = options, onChange }: { label: string; value: string; options: string[]; labels?: Array<string | undefined>; onChange: (value: string) => void }) { return <label className="grid gap-1 text-sm font-semibold">{label}<select className="rounded border border-[#d7cabc] bg-white px-3 py-2 font-normal" value={value} onChange={(event) => onChange(event.target.value)}>{options.map((item, index) => <option key={item} value={item}>{labels[index] || item}</option>)}</select></label>; }
function Panel({ title, children }: { title: string; children: React.ReactNode }) { return <section className="rounded border border-[#d7cabc] bg-[#fffaf2] p-5"><h2 className="text-2xl font-semibold">{title}</h2><div className="mt-4 grid gap-3">{children}</div></section>; }
function Detail({ title, children, onClose }: { title: string; children: React.ReactNode; onClose: () => void }) { return <section className="mt-6 rounded border border-[#d7cabc] bg-[#fffaf2] p-5"><div className="flex items-center justify-between gap-3"><h2 className="text-2xl font-semibold">{title}</h2><button className="rounded border border-[#d7cabc] px-3 py-1 text-sm" onClick={onClose}>閉じる</button></div><div className="mt-4 grid gap-3">{children}</div></section>; }
function Field({ label, value }: { label: string; value: string }) { return <div className="rounded border border-[#d7cabc] bg-white p-3"><p className="text-xs font-semibold text-[#6c5f3d]">{label}</p><p className="mt-1 whitespace-pre-wrap text-sm leading-6">{value || "未設定"}</p></div>; }
function EvidenceCard({ item }: { item: Evidence }) { return <article className="rounded border border-[#d7cabc] bg-white p-3"><p className="text-xs font-semibold text-[#6c5f3d]">{item.source.sourceType} / {item.source.sourceId}</p><p className="mt-1 font-semibold">{item.source.title}</p>{item.claims.map((claim) => <p key={claim.claimId} className="mt-2 text-sm leading-6">{claim.statement} <span className="text-[#6c5f3d]">（confidence: {claim.confidence ?? "未設定"}）</span></p>)}</article>; }
function Empty({ text }: { text: string }) { return <p className="text-sm text-[#5e625c]">{text}</p>; }
function scopeText(value: { tenantId: string; guildId?: string | null; characterId?: string | null; market?: string | null; country?: string | null; locale?: string | null }) { return `tenant: ${value.tenantId} / guild: ${value.guildId || "未設定"} / character: ${value.characterId || "未設定"} / market: ${value.market || "未設定"} / country: ${value.country || "未設定"} / locale: ${value.locale || "未設定"}`; }
