import { env } from "cloudflare:workers";
import { getAdminSession, adminEmail } from "@/app/lib/google-admin-auth";
import { GROWTH_ENGINE_TENANT_ID } from "@/app/lib/growth-engine";
import { GrowthMemoryRepository } from "@/app/lib/growth-memory";
import { GrowthPrecisionService } from "@/app/lib/growth-precision";

async function admin() { const session = await getAdminSession(); return session && session.email.toLowerCase() === adminEmail().toLowerCase() ? session.email : null; }
export async function GET() { const actor = await admin(); if (!actor) return Response.json({ ok: false, error: "Admin authentication required." }, { status: 401 }); try { const memory = new GrowthMemoryRepository(env.DB); const [memories, precision] = await Promise.all([memory.list(GROWTH_ENGINE_TENANT_ID), new GrowthPrecisionService(env.DB).buildReport(GROWTH_ENGINE_TENANT_ID)]); return Response.json({ ok: true, memories, precision }, { headers: { "Cache-Control": "no-store" } }); } catch (error) { return Response.json({ ok: false, error: error instanceof Error ? error.message : "Learning read failed." }, { status: 400 }); } }
export async function POST(request: Request) { const actor = await admin(); if (!actor) return Response.json({ ok: false, error: "Admin authentication required." }, { status: 401 }); const body = await request.json().catch(() => null) as Record<string, unknown> | null; if (!body) return Response.json({ ok: false, error: "Invalid JSON body." }, { status: 400 }); try { const memory = new GrowthMemoryRepository(env.DB); const action = String(body.action || ""); const tenant = String(body.tenant_id || GROWTH_ENGINE_TENANT_ID); if (action === "createFromExperiment") return Response.json({ ok: true, result: await memory.createFromExperiment(tenant, String(body.experiment_id || ""), actor) }, { status: 201 }); if (action === "reuse") return Response.json({ ok: true, memory: await memory.recordReuse(tenant, String(body.knowledge_id || ""), actor, body.reused_from as string | undefined) }); if (action === "supersede") return Response.json({ ok: true, memory: await memory.markSuperseded(tenant, String(body.knowledge_id || ""), String(body.superseded_by || ""), actor, String(body.reason || "")) }); return Response.json({ ok: false, error: "Unsupported learning action." }, { status: 400 }); } catch (error) { return Response.json({ ok: false, error: error instanceof Error ? error.message : "Learning action failed." }, { status: 400 }); } }
