import Link from "next/link";
import { getStudioOSSnapshot } from "@/app/lib/studioos-system";
import { resolveTenantMarket } from "@/app/lib/studioos-market";

export const metadata = { title: "StudioOS | Raven Admin" };

export default function StudioOSAdminPage() {
  const snapshot = getStudioOSSnapshot("raven-oracle", { environment: "local" });
  const market = resolveTenantMarket("raven-oracle");
  return <main className="admin-dashboard"><div className="admin-shell"><nav className="admin-nav"><Link className="admin-link" href="/admin/">管理ダッシュボード</Link><Link className="admin-link" href="/admin/studioos/version-center/">Version Center</Link></nav><header className="admin-hero"><p className="admin-kicker">StudioOS / Read-only</p><h1 className="admin-title">Version & Entitlements</h1><p className="admin-lead">Version、Tenant Schema、Engine、Feature Entitlement、Market Personaを読み取り確認します。ここから設定変更や自動Updateは行いません。</p></header><section className="admin-summary"><Stat label="StudioOS" value={snapshot.version.studioOsVersion} note={snapshot.version.status} /><Stat label="Market" value={market.market.marketId} note={market.market.locale} /><Stat label="Tenant Schema" value={String(snapshot.version.tenantSchemaVersion)} note={snapshot.version.compatibility} /><Stat label="Plan" value={snapshot.plan} note={snapshot.version.tenantId} /><Stat label="Build Commit" value={snapshot.build.buildCommit || "unknown"} note={snapshot.build.environment} /></section><section className="admin-workspace"><div className="admin-panel"><h2>Market / Character</h2><div className="admin-list"><Row title="Character Core" meta={market.character.characterId} body={market.character.canonicalName} /><Row title="Market Persona" meta={`${market.persona.marketId} / ${market.persona.locale}`} body={`${market.persona.tone || "unknown"} / CTA ${market.persona.ctaStyle || "unknown"}`} /><Row title="Localization" meta={`${market.market.country} / ${market.market.currency}`} body={`${market.market.timezone} / ${market.market.dateFormat}`} /></div></div><div className="admin-panel"><h2>Engine Versions</h2><div className="admin-list">{Object.entries(snapshot.engines).map(([name, version]) => <Row key={name} title={name} meta={version} body="Read-only manifest" />)}</div></div><div className="admin-panel"><h2>Feature Entitlements</h2><div className="admin-list">{snapshot.entitlements.map((item) => <Row key={item.feature} title={item.feature} meta={`${item.allowed ? "ALLOW" : "DENY"} / ${item.source}`} body={`${item.reason} / plan ${item.planDefault ? "allow" : "deny"} / flag ${item.featureFlag === null ? "inherit" : item.featureFlag ? "on" : "off"} / override ${item.tenantOverride}`} />)}</div></div></section><p className="admin-muted">Migration Ledger: {snapshot.migration.migrationLedgerRef || "unknown"}</p></div></main>;
}

function Stat({ label, value, note }: { label: string; value: string; note: string }) { return <div className="admin-stat"><p>{label}</p><strong>{value}</strong><span>{note}</span></div>; }
function Row({ title, meta, body }: { title: string; meta: string; body: string }) { return <article className="admin-row"><p className="admin-row-meta">{meta}</p><h3>{title}</h3><p>{body}</p></article>; }
