import { env } from "cloudflare:workers";
import { getAdminSession, adminEmail } from "@/app/lib/google-admin-auth";
import { GROWTH_ENGINE_TENANT_ID } from "@/app/lib/growth-engine";
import { listRecommendations, saveRecommendation, getRecommendationSummary } from "@/app/lib/growth-recommendations";

async function admin() { const session = await getAdminSession(); return session && session.email.toLowerCase() === adminEmail().toLowerCase(); }
function tenant(value: string | null) { if ((value || GROWTH_ENGINE_TENANT_ID) !== GROWTH_ENGINE_TENANT_ID) throw new Error("Invalid tenant_id."); return GROWTH_ENGINE_TENANT_ID; }
export async function GET(request: Request) { if (!(await admin())) return Response.json({ ok: false, error: "Admin authentication required." }, { status: 401 }); try { const url = new URL(request.url); const tenantId = tenant(url.searchParams.get("tenantId")); const recommendations = await listRecommendations(env.DB, tenantId); return Response.json({ ok: true, summary: await getRecommendationSummary(env.DB, tenantId), recommendations }, { headers: { "Cache-Control": "no-store" } }); } catch (error) { return Response.json({ ok: false, error: error instanceof Error ? error.message : "Recommendation API failed." }, { status: 400 }); } }
export async function POST(request: Request) { if (!(await admin())) return Response.json({ ok: false, error: "Admin authentication required." }, { status: 401 }); const body = await request.json().catch(() => null) as Record<string, unknown> | null; if (!body) return Response.json({ ok: false, error: "Invalid JSON body." }, { status: 400 }); try { const tenantId = tenant(String(body.tenantId ?? body.tenant_id ?? GROWTH_ENGINE_TENANT_ID)); const patternKey = String(body.patternKey ?? body.pattern_key ?? ""); const action = String(body.action || "").toLowerCase(); if (!patternKey || !["save", "dismiss"].includes(action)) throw new Error("patternKey and save or dismiss action are required."); const recommendation = await saveRecommendation(env.DB, patternKey, body, tenantId, action === "save" ? "SAVED" : "DISMISSED"); return Response.json({ ok: true, recommendation }); } catch (error) { return Response.json({ ok: false, error: error instanceof Error ? error.message : "Recommendation action failed." }, { status: 400 }); } }
