import Link from "next/link";
import { buildVersionCenterEntries } from "@/app/lib/studioos-registry";

export default async function VersionCenterTenantPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const entry = buildVersionCenterEntries({ includeFixtures: true }).find((item) => item.tenant.tenantId === id);
  if (!entry) return <main className="admin-dashboard"><div className="admin-shell"><p>Tenant not found.</p></div></main>;
  return <main className="admin-dashboard"><div className="admin-shell"><nav className="admin-nav"><Link className="admin-link" href="/admin/studioos/version-center/">Version Center</Link></nav><header className="admin-hero"><p className="admin-kicker">Tenant Detail / Read-only</p><h1 className="admin-title">{entry.tenant.displayName}</h1><p className="admin-lead">{entry.tenant.tenantId} / {entry.guild.guildName} / {entry.tenant.status}</p></header><section className="admin-summary"><Stat label="StudioOS" value={entry.version.studioOsVersion} note={entry.version.status} /><Stat label="Market" value={entry.tenant.market || "unknown"} note={entry.tenant.locale || "unknown"} /><Stat label="Schema" value={String(entry.version.tenantSchemaVersion)} note={entry.version.compatibility} /><Stat label="Plan" value={entry.plan} note={`${entry.enabledFeatureCount} allow / ${entry.deniedFeatureCount} deny`} /><Stat label="Worker" value={entry.worker?.workerName || "unknown"} note={entry.worker?.status || "unknown"} /></section><section className="admin-workspace"><Panel title="Identity"><Row label="Tenant" value={entry.tenant.tenantKey} /><Row label="Guild" value={entry.guild.guildName} /><Row label="Character Core" value={entry.tenant.characterCoreId || entry.tenant.characterId || "unknown"} /><Row label="Market Persona" value={entry.tenant.marketPersonaId || "unknown"} /></Panel><Panel title="Localization"><Row label="Country" value={entry.tenant.country || "unknown"} /><Row label="Locale" value={entry.tenant.locale || "unknown"} /><Row label="Currency" value={entry.tenant.currency || "unknown"} /><Row label="Timezone" value={entry.tenant.timezone || "unknown"} /></Panel><Panel title="Worker"><Row label="Name" value={entry.worker?.workerName || "unknown"} /><Row label="Provider" value={entry.worker?.provider || "unknown"} /><Row label="Public URL" value={entry.worker?.publicUrl || "unknown"} /><Row label="Last Deploy" value={entry.lastDeploy || "unknown"} /></Panel><Panel title="Migration"><Row label="State" value={entry.migration.migrationState} /><Row label="Version" value={entry.migration.d1MigrationVersion || "unknown"} /><Row label="Ledger" value={entry.migration.migrationLedgerRef || "unknown"} /></Panel><Panel title="Entitlements">{entry.entitlements.length ? entry.entitlements.map((item) => <Row key={item.feature} label={item.feature} value={`${item.allowed ? "ALLOW" : "DENY"} / ${item.reason}`} />) : <p className="admin-muted">Fixture entitlement detail is intentionally read-only and not connected to a tenant resolver.</p>}</Panel></section><p className="admin-muted">Update / deploy / migration requires separate human approval and is not available from this page.</p></div></main>;
}

function Panel({ title, children }: { title: string; children: React.ReactNode }) { return <div className="admin-panel"><h2>{title}</h2><div className="admin-list">{children}</div></div>; }
function Row({ label, value }: { label: string; value: string }) { return <article className="admin-row"><p className="admin-row-meta">{label}</p><p>{value}</p></article>; }
function Stat({ label, value, note }: { label: string; value: string; note: string }) { return <div className="admin-stat"><p>{label}</p><strong>{value}</strong><span>{note}</span></div>; }
