import { env } from "cloudflare:workers";
import { getAdminSession, adminEmail } from "@/app/lib/google-admin-auth";
import { GROWTH_ENGINE_TENANT_ID } from "@/app/lib/growth-engine";
import { listIdeaCandidates, reviewIdeaCandidate } from "@/app/lib/growth-idea-bridge";

async function admin() { const session = await getAdminSession(); return session && session.email.toLowerCase() === adminEmail().toLowerCase(); }
function tenant(value: unknown) { const id = String(value || GROWTH_ENGINE_TENANT_ID); if (id !== GROWTH_ENGINE_TENANT_ID) throw new Error("Invalid tenant_id."); return id; }
export async function GET(request: Request) { if (!(await admin())) return Response.json({ ok: false, error: "Admin authentication required." }, { status: 401 }); try { const url = new URL(request.url); const tenantId = tenant(url.searchParams.get("tenantId")); return Response.json({ ok: true, candidates: await listIdeaCandidates(env.DB, tenantId) }, { headers: { "Cache-Control": "no-store" } }); } catch (error) { return Response.json({ ok: false, error: error instanceof Error ? error.message : "Idea API failed." }, { status: 400 }); } }
export async function POST(request: Request) { if (!(await admin())) return Response.json({ ok: false, error: "Admin authentication required." }, { status: 401 }); const body = await request.json().catch(() => null) as Record<string, unknown> | null; if (!body) return Response.json({ ok: false, error: "Invalid JSON body." }, { status: 400 }); try { const tenantId = tenant(body.tenantId ?? body.tenant_id); const patternKey = String(body.sourcePatternKey ?? body.source_pattern_key ?? body.patternKey ?? ""); const action = String(body.action || "generate").toLowerCase(); if (!patternKey) throw new Error("sourcePatternKey is required."); if (action === "generate") return Response.json({ ok: true, candidates: (await listIdeaCandidates(env.DB, tenantId)).filter((item) => item.sourcePatternKey === patternKey) }); if (!["save", "dismiss"].includes(action)) throw new Error("Only generate, save, and dismiss are supported."); return Response.json({ ok: true, candidate: await reviewIdeaCandidate(env.DB, patternKey, body, tenantId, action === "save" ? "SAVED" : "DISMISSED") }); } catch (error) { return Response.json({ ok: false, error: error instanceof Error ? error.message : "Idea review failed." }, { status: 400 }); } }
