"use client";
import Link from "next/link";
import { useEffect, useState } from "react";

type Draft = { draftId: string; ideaCandidateId: string; status: string; title: string; hook: string; concept: string; contentType: string; caption: string; cta: string; hashtags: string[]; recommendedDuration: number; recommendedTemplate: string; deckCandidate: string; cardSelectionStrategy: string; backgroundCandidate: string; bgmMood: string; whatToTest: string[]; structure: Record<string, string>; traceability: Record<string, unknown>; scope: Record<string, string> };
export default function SnsDraftPage({ params }: { params: Promise<{ id: string }> }) { const [draft, setDraft] = useState<Draft | null>(null); const [error, setError] = useState(""); const [saving, setSaving] = useState(false); useEffect(() => { void params.then(({ id }) => fetch(`/api/sns/drafts/${id}`, { cache: "no-store" }).then(async (response) => { const body = await response.json(); if (!response.ok) setError(body.error || "Draftを読み込めません。"); else setDraft(body.draft); }).catch(() => setError("Draftを読み込めません。"))); }, [params]);
  async function save() { if (!draft) return; setSaving(true); const response = await fetch(`/api/sns/drafts/${draft.draftId}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(draft) }); const body = await response.json(); setSaving(false); if (!response.ok) setError(body.error || "保存できません。"); else setDraft(body.draft); }
  function update(key: keyof Draft, value: unknown) { setDraft((current) => current ? { ...current, [key]: value } : current); }
  if (error) return <main className="min-h-screen bg-[#f5f0e8] p-8"><p className="rounded border border-red-300 bg-red-50 p-4 text-red-700">{error}</p></main>;
  if (!draft) return <main className="min-h-screen bg-[#f5f0e8] p-8 text-[#20241f]">読み込み中...</main>;
  return <main className="min-h-screen bg-[#f5f0e8] px-5 py-8 text-[#20241f]"><div className="mx-auto max-w-5xl"><Link className="text-sm font-semibold text-[#596d51]" href="/admin/sns/ideas">投稿アイデアへ戻る</Link><header className="mt-5 border-b border-[#d7cabc] pb-6"><p className="text-sm font-semibold uppercase text-[#6c5f3d]">SNS Content Draft / {draft.status}</p><h1 className="mt-2 text-3xl font-semibold">SNSコンテンツ下書き</h1><p className="mt-2 text-sm text-[#5e625c]">Idea Candidateから作成した制作前の下書きです。動画生成・投稿・予約には接続されていません。</p></header><section className="mt-6 grid gap-4 rounded border border-[#d7cabc] bg-[#fffaf2] p-5 md:grid-cols-2"><Field label="タイトル" value={draft.title} onChange={(value) => update("title", value)} /><Field label="Hook" value={draft.hook} onChange={(value) => update("hook", value)} /><Field label="Caption" value={draft.caption} onChange={(value) => update("caption", value)} area /><Field label="CTA" value={draft.cta} onChange={(value) => update("cta", value)} /><Field label="Hashtags（空白区切り）" value={draft.hashtags.join(" ")} onChange={(value) => update("hashtags", value.split(/\s+/).filter(Boolean))} /><Field label="推奨尺（秒）" value={String(draft.recommendedDuration)} onChange={(value) => update("recommendedDuration", Number(value))} /><Field label="Template候補" value={draft.recommendedTemplate} onChange={(value) => update("recommendedTemplate", value)} /><div className="grid gap-2 text-sm"><span className="font-semibold">Concept</span><p className="rounded border border-[#d7cabc] bg-white p-3 text-sm leading-6">{draft.concept}</p></div></section><section className="mt-6 grid gap-4 md:grid-cols-2"><Preview title="構成Preview" value={JSON.stringify(draft.structure, null, 2)} /><Preview title="Scope / Traceability" value={JSON.stringify({ scope: draft.scope, traceability: draft.traceability, contentType: draft.contentType, deckCandidate: draft.deckCandidate, cardSelectionStrategy: draft.cardSelectionStrategy, backgroundCandidate: draft.backgroundCandidate, bgmMood: draft.bgmMood, whatToTest: draft.whatToTest }, null, 2)} /></section><div className="mt-6 flex flex-wrap gap-3"><Link className="rounded border border-[#6c5f3d] px-4 py-3 text-sm font-semibold text-[#6c5f3d]" href={`/admin/sns/drafts/${draft.draftId}/preview`}>Preview</Link><button className="rounded border border-[#596d51] bg-[#596d51] px-4 py-3 text-sm font-semibold text-white" onClick={() => void save()} disabled={saving}>{saving ? "保存中..." : "下書きを保存"}</button><button className="rounded border border-[#9a5c52] px-4 py-3 text-sm font-semibold text-[#9a5c52]" onClick={() => { update("status", "DISCARDED"); void save(); }}>破棄</button></div></div></main>; }
function Field({ label, value, onChange, area = false }: { label: string; value: string; onChange: (value: string) => void; area?: boolean }) { return <label className="grid gap-2 text-sm font-semibold"><span>{label}</span>{area ? <textarea className="admin-field min-h-32" value={value} onChange={(event) => onChange(event.target.value)} /> : <input className="admin-field" value={value} onChange={(event) => onChange(event.target.value)} />}</label>; }
function Preview({ title, value }: { title: string; value: string }) { return <section className="rounded border border-[#d7cabc] bg-[#fffaf2] p-5"><h2 className="font-semibold">{title}</h2><pre className="mt-3 overflow-auto whitespace-pre-wrap text-xs leading-5 text-[#5e625c]">{value}</pre></section>; }
