import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { DatabaseSync } from "node:sqlite";
import test from "node:test";
import { GrowthMemoryRepository } from "../app/lib/growth-memory.ts";
import { GrowthPrecisionService } from "../app/lib/growth-precision.ts";

function adapter(db) { return { prepare(sql) { return { bind(...values) { const statement = db.prepare(sql); return { async all() { return { results: statement.all(...values) }; }, async first() { return statement.get(...values) || null; }, async run() { return statement.run(...values); } }; } }; } }; }
function fixture() { const db = new DatabaseSync(":memory:"); for (const file of ["0013_growth_experiment_manager.sql", "0005_growth_engine_v2_v3.sql", "0029_growth_hypotheses.sql", "0030_growth_proposals.sql", "0031_growth_proposal_experiment_link.sql", "0032_growth_memory_precision.sql"]) db.exec(readFileSync(new URL(`../drizzle/${file}`, import.meta.url), "utf8")); return { db, adapter: adapter(db) }; }
function experiment(db, id, resultStatus, actual = 14) { db.prepare(`INSERT INTO growth_experiments (experiment_id, tenant_id, title, hypothesis, primary_metric, target_type, primary_kpi, primary_kpi_direction, baseline_value, target_value, measured_value, result_status, status, confidence_score, sample_size, target_id) VALUES (?, 'raven-oracle', ?, 'Improve conversion', 'conversion_rate', 'CONTENT', 'conversion_rate', 'increase', 10, 15, ?, ?, 'COMPLETED', 70, 20, 'blog')`).run(id, id, actual, resultStatus); }

test("experiment results become idempotent Growth Memory with prediction fields", async () => { const state = fixture(); experiment(state.db, "exp-win", "WIN"); const repository = new GrowthMemoryRepository(state.adapter); const first = await repository.createFromExperiment("raven-oracle", "exp-win", "tester"); const second = await repository.createFromExperiment("raven-oracle", "exp-win", "tester"); assert.equal(first.created, true); assert.equal(second.created, false); assert.equal(first.memory.successLevel, "success"); assert.equal(first.memory.predictionError, -1); assert.equal(first.memory.absoluteError, 1); assert.equal(first.memory.directionCorrect, true); });
test("failure memory exposes suppression candidate without automatic suppression", async () => { const state = fixture(); experiment(state.db, "exp-loss-1", "LOSS", 8); experiment(state.db, "exp-loss-2", "LOSS", 7); const repository = new GrowthMemoryRepository(state.adapter); const first = await repository.createFromExperiment("raven-oracle", "exp-loss-1"); await repository.createFromExperiment("raven-oracle", "exp-loss-2"); const candidate = await repository.suppressionCandidate("raven-oracle", first.memory.actionSignature); assert.equal(candidate.candidate, true); assert.equal(candidate.priorFailures, 2); assert.equal(candidate.memories.every((item) => !item.suppressed), true); });
test("reuse and superseded history are tenant-scoped relations", async () => { const state = fixture(); experiment(state.db, "exp-reuse", "WIN"); const repository = new GrowthMemoryRepository(state.adapter); const created = await repository.createFromExperiment("raven-oracle", "exp-reuse"); const reused = await repository.recordReuse("raven-oracle", created.memory.id, "reviewer", "future-action"); assert.equal(reused.reuseCount, 1); const replacement = crypto.randomUUID(); const superseded = await repository.markSuperseded("raven-oracle", created.memory.id, replacement, "reviewer", "newer evidence"); assert.equal(superseded.supersededBy, replacement); await assert.rejects(() => repository.get("unknown-tenant", created.memory.id), /Unknown tenant/); });
test("precision report calculates rates, errors and small-sample calibration guard", async () => { const state = fixture(); experiment(state.db, "exp-report-win", "WIN", 14); experiment(state.db, "exp-report-loss", "LOSS", 8); const repository = new GrowthMemoryRepository(state.adapter); await repository.createFromExperiment("raven-oracle", "exp-report-win"); await repository.createFromExperiment("raven-oracle", "exp-report-loss"); const report = await new GrowthPrecisionService(state.adapter).buildReport("raven-oracle"); assert.equal(report.experimentSuccessRate, 0.5); assert.equal(report.meanAbsoluteError, 4); assert.equal(report.directionAccuracy, 0.5); assert.equal(report.calibration.every((bucket) => bucket.reliable === false), true); assert.equal(report.calibration.every((bucket) => bucket.reliability === "calibration_unreliable_small_sample"), true); });
test("legacy knowledge rows remain readable after additive migration", async () => { const state = fixture(); state.db.prepare("INSERT INTO growth_knowledge_items (id, tenant_id, item_type, title, content) VALUES (?, ?, ?, ?, ?)").run("legacy-memory", "raven-oracle", "manual", "Legacy", "Existing item"); const row = await new GrowthMemoryRepository(state.adapter).get("raven-oracle", "legacy-memory"); assert.equal(row.successLevel, "inconclusive"); assert.equal(row.reuseCount, 0); assert.equal(row.suppressed, false); });
