import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import { recommendationType, primaryGoal, recommendationPriority, stateFingerprint } from "../app/lib/growth-recommendation-policy.ts";

const pattern = (overrides = {}) => ({ resultClass: "positive", maturity: "ESTABLISHED", confidence: .8, evidenceSufficiency: "STRONG", experimentCount: 3, sampleSize: 300, consistency: .8, decayScore: .9, metricAvailability: "AVAILABLE", revenueKinds: ["MEASURED"], scope: { metric: "save_rate", locale: "ja-JP", market: "JP" }, lastTestedAt: new Date().toISOString(), ...overrides });
test("classifies learning states without execution semantics", () => { assert.equal(recommendationType(pattern()), "PROVEN_REUSE"); assert.equal(recommendationType(pattern({ maturity: "EMERGING", confidence: .6 })), "EMERGING_TEST"); assert.equal(recommendationType(pattern({ maturity: "PROVISIONAL", confidence: .3 })), "COLLECT_MORE_EVIDENCE"); assert.equal(recommendationType(pattern({ maturity: "DECAYING", decayScore: .2 })), "RETEST_DECAYING"); assert.equal(recommendationType(pattern({ resultClass: "negative", maturity: "EMERGING" })), "IMPROVEMENT_TEST"); assert.equal(recommendationType(pattern({ resultClass: "insufficient_learning", maturity: "PROVISIONAL" })), "COLLECT_MORE_EVIDENCE"); });
test("separates primary goals and revenue availability", () => { assert.equal(primaryGoal(pattern({ scope: { metric: "views" } })), "VIRAL"); assert.equal(primaryGoal(pattern({ scope: { metric: "conversion_rate" } })), "CONVERSION"); assert.equal(primaryGoal(pattern({ scope: { metric: "revenue" }, revenueKinds: ["ESTIMATED"] })), "LEARNING"); assert.equal(primaryGoal(pattern({ scope: { metric: "revenue" }, revenueKinds: ["MEASURED"] })), "REVENUE"); });
test("small sample cannot produce a strong reuse priority", () => { const small = pattern({ experimentCount: 1, sampleSize: 5, confidence: .45, maturity: "PROVISIONAL", evidenceSufficiency: "WEAK" }); assert.equal(recommendationType(small), "COLLECT_MORE_EVIDENCE"); assert.ok(recommendationPriority(small) < .5); });
test("fatigue and decay alter recommendation", () => { const fatigued = pattern({ experimentCount: 5, lastTestedAt: new Date().toISOString() }); assert.equal(recommendationType(fatigued), "IMPROVEMENT_TEST"); assert.equal(recommendationType(pattern({ maturity: "DECAYING", decayScore: .2 })), "RETEST_DECAYING"); });
test("state fingerprint supports idempotent recommendation identity", () => { assert.equal(stateFingerprint(pattern()), stateFingerprint(pattern())); assert.notEqual(stateFingerprint(pattern()), stateFingerprint(pattern({ confidence: .7 }))); });
test("recommendation layer has only review actions and no execution integration", () => { const source = fs.readFileSync(new URL("../app/lib/growth-recommendations.ts", import.meta.url), "utf8"); assert.match(source, /SAVED/); assert.match(source, /DISMISSED/); assert.doesNotMatch(source, /createExperiment|autonomous|publish|external API/i); });
