import Link from "next/link";
import { buildVersionCenterEntries } from "@/app/lib/studioos-registry";

export const metadata = { title: "Version Center | Raven Admin" };
const cellStyle = { borderBottom: "1px solid #e1d6c8", padding: "12px 10px", textAlign: "left" as const, fontSize: 13 };

export default function VersionCenterPage() {
  const entries = buildVersionCenterEntries({ includeFixtures: true });
  return <main className="admin-dashboard"><div className="admin-shell"><nav className="admin-nav"><Link className="admin-link" href="/admin/studioos/">StudioOS</Link><Link className="admin-link" href="/admin/">管理ダッシュボード</Link></nav><header className="admin-hero"><p className="admin-kicker">Fortune Studio Platform / Read-only</p><h1 className="admin-title">Version Center</h1><p className="admin-lead">Guild、Tenant、Workerのversion・schema・migration・entitlementを読み取り確認します。Update、Deploy、Migrationは実行しません。</p></header><section className="admin-panel" style={{ marginTop: 24, overflowX: "auto" }}><table style={{ width: "100%", borderCollapse: "collapse", minWidth: 920 }}><thead><tr>{["Tenant", "Guild", "Worker", "StudioOS", "Schema", "Build", "Plan", "Status", "Compatibility", "Last Deploy"].map((label) => <th key={label} style={cellStyle}>{label}</th>)}</tr></thead><tbody>{entries.map((entry) => <tr key={entry.tenant.tenantId}><td style={cellStyle}><Link href={`/admin/studioos/version-center/tenants/${entry.tenant.tenantId}`}>{entry.tenant.displayName}</Link>{entry.tenant.isFixture ? <small> fixture</small> : null}</td><td style={cellStyle}>{entry.guild.guildName}</td><td style={cellStyle}>{entry.worker?.workerName || "unknown"}</td><td style={cellStyle}>{entry.version.studioOsVersion}</td><td style={cellStyle}>{entry.version.tenantSchemaVersion}</td><td style={cellStyle}>{entry.version.buildCommit || "unknown"}</td><td style={cellStyle}>{entry.plan}</td><td style={cellStyle}>{entry.version.status}</td><td style={cellStyle}>{entry.version.compatibility}</td><td style={cellStyle}>{entry.lastDeploy || "unknown"}</td></tr>)}</tbody></table></section><p className="admin-muted">Fixture rows are local read-model examples only. They do not represent created production tenants or workers.</p></div></main>;
}
