import http from "node:http";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { randomUUID } from "node:crypto";
import { join } from "node:path";
import { spawn } from "node:child_process";

const port = Number(process.env.PORT || 8080);
const token = String(process.env.RENDERER_TOKEN || "").trim();
const root = "/tmp/raven-renderer";
await mkdir(root, { recursive: true });
const json = (res, body, status = 200) => { res.writeHead(status, { "content-type": "application/json", "cache-control": "no-store" }); res.end(JSON.stringify(body)); };
const safe = (v, n = 500) => String(v ?? "").replace(/[\r\n]/g, " ").trim().slice(0, n);
const ass = (v) => safe(v).replaceAll("\\", "\\\\").replaceAll("{", "\\{").replaceAll("}", "\\}").replaceAll("\n", "\\N");
async function readBody(req) { const chunks = []; for await (const c of req) chunks.push(c); return JSON.parse(Buffer.concat(chunks).toString("utf8") || "{}"); }
async function download(url, path) { const parsed = new URL(url); if (parsed.protocol !== "https:") throw new Error("source URL must use https"); const response = await fetch(parsed); if (!response.ok) throw new Error(`source download ${response.status}`); await writeFile(path, Buffer.from(await response.arrayBuffer())); }
async function render(input, output, p) { const title = ass(p.theme || p.title || "今日の3択占い"); const hook = ass(p.hook || "直感で1枚選んでください"); const cta = ass(p.cta || "詳しい鑑定はプロフィールから"); const results = ass((p.cards || []).map((c, i) => `${String.fromCharCode(65 + i)}: ${c.reading || c.name || "結果"}`).join("  ")); const assPath = `${output}.ass`; await writeFile(assPath, `[Script Info]\nScriptType: v4.00+\nPlayResX: 1080\nPlayResY: 1920\n\n[V4+ Styles]\nFormat: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding\nStyle: Main,Noto Sans CJK JP,88,&H00FFFFFF,&H00FFFFFF,&HAA000000,&H99000000,-1,0,0,0,100,100,0,0,3,5,0,5,40,40,0,1\nStyle: Sub,Noto Sans CJK JP,62,&H00FFFFFF,&H00FFFFFF,&HAA000000,&H99000000,0,0,0,0,100,100,0,0,3,4,0,2,40,40,320,1\n[Events]\nFormat: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text\nDialogue: 0,0:00:00.00,0:00:20.00,Main,,0,0,0,,${title}\\N${hook}\nDialogue: 0,0:00:05.00,0:00:17.00,Sub,,0,0,0,,${results}\nDialogue: 1,0:00:17.00,0:00:20.00,Main,,0,0,0,,${cta}\n`, "utf8"); const filter = `scale=1080:1920:force_original_aspect_ratio=increase,crop=1080:1920,subtitles='${assPath}'`; await new Promise((resolve, reject) => { const child = spawn("ffmpeg", ["-y", "-hide_banner", "-loglevel", "error", "-i", input, "-t", "20", "-vf", filter, "-c:v", "libx264", "-pix_fmt", "yuv420p", "-b:v", "3500k", "-c:a", "aac", "-b:a", "128k", "-movflags", "+faststart", output]); let error = ""; child.stderr.on("data", c => { error += c; }); child.on("error", reject); child.on("close", code => code === 0 ? resolve() : reject(new Error(error || `ffmpeg exit ${code}`))); }); }
const server = http.createServer(async (req, res) => { try { if (token && req.headers.authorization !== `Bearer ${token}`) return json(res, { error: "Unauthorized" }, 401); if (req.method === "GET" && req.url === "/health") return json(res, { ok: true, renderer: "raven-ffmpeg" }); if (req.method === "GET" && req.url?.startsWith("/outputs/")) { const id = req.url.split("/").pop(); const data = await readFile(join(root, `${id}.mp4`)); res.writeHead(200, { "content-type": "video/mp4", "cache-control": "public, max-age=300" }); return res.end(data); } if (req.method !== "POST" || req.url !== "/jobs") return json(res, { error: "Not found" }, 404); const input = await readBody(req); const jobId = safe(input.jobId || randomUUID(), 120); const p = input.payload || {}; const sourceUrl = safe(p.background || p.sourceUrl, 1000); if (!sourceUrl) return json(res, { error: "payload.background or payload.sourceUrl is required" }, 422); const inputPath = join(root, `${jobId}-input.mp4`); const outputPath = join(root, `${jobId}.mp4`); await download(sourceUrl, inputPath); await render(inputPath, outputPath, p); return json(res, { rendererJobId: jobId, status: "completed", outputUrl: `${process.env.PUBLIC_BASE_URL || `http://localhost:${port}`}/outputs/${jobId}` }); } catch (error) { return json(res, { error: error instanceof Error ? error.message : "render_failed" }, 500); } });
server.listen(port, "0.0.0.0");
