import Link from "next/link";
type Pattern = { patternKey: string; resultClass: string; maturity: string; confidence: number; scope: Record<string, string>; experimentCount: number; sampleAvailability: string; sampleSize: number; consistency: number; decayScore: number; sourceEvidenceCount: number; claimCount: number; evidenceSufficiency: string; missingEvidence: string[]; revenueKinds: string[]; metricAvailability: string };

async function load() { const response = await fetch(`${process.env.NEXT_PUBLIC_SITE_URL || ""}/api/growth-engine/learning`, { cache: "no-store" }).catch(() => null); return response?.ok ? response.json() : { patterns: [], summary: {} }; }
export const metadata = { title: "Learning Patterns | Raven Blackwood" };
export default async function LearningPage() {
  const data = await load(); const patterns = (data.patterns || []) as Pattern[]; const summary = data.summary || {};
  return <main className="min-h-screen bg-[#f5f0e8] px-5 py-8 text-[#20241f]"><div className="mx-auto max-w-7xl"><Link className="text-sm font-semibold text-[#596d51]" href="/admin/growth">Growth Engineへ戻る</Link><header className="mt-5 border-b border-[#d7cabc] pb-6"><p className="text-sm font-semibold uppercase text-[#6c5f3d]">Evidence-derived read-only view</p><h1 className="mt-2 text-4xl font-semibold">Learning Patterns</h1><p className="mt-3 text-[#5e625c]">実験結果とEvidenceから導出した傾向です。推薦や自動実行はこの画面では行いません。</p></header><section className="mt-8 grid gap-4 md:grid-cols-3"><Summary title="Patterns" value={String(summary.patternCount || 0)} /><Summary title="Latest tested" value={summary.latestTestedAt || "未計測"} /><Summary title="Tenant" value={summary.tenantId || "raven-oracle"} /></section><section className="mt-8 grid gap-4">{patterns.map((pattern) => <article key={pattern.patternKey} className="rounded border border-[#d7cabc] bg-[#fffaf2] p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-semibold uppercase text-[#6c5f3d]">{pattern.resultClass} / {pattern.maturity}</p><h2 className="mt-1 font-semibold">{pattern.scope.metric || "metric未設定"} / {pattern.scope.platform || "platform未設定"}</h2></div><span className="text-sm text-[#5e625c]">confidence {pattern.confidence}</span></div><p className="mt-3 text-sm text-[#5e625c]">実験 {pattern.experimentCount}件 / sample {pattern.sampleAvailability}: {pattern.sampleSize} / consistency {pattern.consistency} / decay {pattern.decayScore}</p><p className="mt-2 text-sm text-[#5e625c]">scope: {Object.entries(pattern.scope).map(([key, value]) => `${key}=${value}`).join(" / ")}</p><p className="mt-2 text-sm text-[#5e625c]">Evidence {pattern.sourceEvidenceCount} source / {pattern.claimCount} claims / sufficiency {pattern.evidenceSufficiency}</p><p className="mt-2 text-sm text-[#5e625c]">不足: {pattern.missingEvidence.join(", ") || "なし"}</p><p className="mt-2 text-sm text-[#5e625c]">revenue: {pattern.revenueKinds.join(", ") || "UNAVAILABLE"} / metric: {pattern.metricAvailability}</p></article>)}{!patterns.length ? <p className="rounded border border-[#d7cabc] bg-[#fffaf2] p-5 text-sm text-[#5e625c]">Evidence-backedな学習パターンはまだありません。</p> : null}</section></div></main>;
}
function Summary({ title, value }: { title: string; value: string }) { return <div className="rounded border border-[#d7cabc] bg-[#fffaf2] p-5"><p className="text-sm font-semibold uppercase text-[#6c5f3d]">{title}</p><p className="mt-2 text-xl font-semibold">{value}</p></div>; }
