"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
type Pattern = { patternKey: string; resultClass: string; maturity: string; confidence: number; scope: Record<string, string>; experimentCount: number; sampleAvailability: string; sampleSize: number; consistency: number; decayScore: number; sourceEvidenceCount: number; claimCount: number; evidenceSufficiency: string; missingEvidence: string[]; revenueKinds: string[]; metricAvailability: string };

export default function LearningPage() {
  const [data, setData] = useState<{ patterns: Pattern[]; summary: Record<string, unknown>; recommendations: Recommendation[]; candidates: IdeaCandidate[] }>({ patterns: [], summary: {}, recommendations: [], candidates: [] });
  const [error, setError] = useState("");
  async function refresh() { const [recommendationResponse, ideaResponse] = await Promise.all([fetch("/api/growth-engine/learning/recommendations", { cache: "no-store" }), fetch("/api/growth-engine/learning/ideas", { cache: "no-store" })]); const body = await recommendationResponse.json(); const ideas = await ideaResponse.json(); if (!recommendationResponse.ok || !ideaResponse.ok) { setError(body.error || ideas.error || "読み込みに失敗しました。"); return; } setData({ ...body, candidates: ideas.candidates || [] }); }
  useEffect(() => { let active = true; void Promise.all([fetch("/api/growth-engine/learning/recommendations", { cache: "no-store" }), fetch("/api/growth-engine/learning/ideas", { cache: "no-store" })]).then(async ([recommendationResponse, ideaResponse]) => { const body = await recommendationResponse.json(); const ideas = await ideaResponse.json(); if (!active) return; if (!recommendationResponse.ok || !ideaResponse.ok) setError(body.error || ideas.error || "読み込みに失敗しました。"); else setData({ ...body, candidates: ideas.candidates || [] }); }).catch(() => { if (active) setError("読み込みに失敗しました。"); }); return () => { active = false; }; }, []);
  async function review(patternKey: string, action: "save" | "dismiss") { const response = await fetch("/api/growth-engine/learning/recommendations", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ patternKey, action }) }); if (!response.ok) { const body = await response.json(); setError(body.error || "更新に失敗しました。"); return; } await refresh(); }
  async function reviewIdea(sourcePatternKey: string, action: "save" | "dismiss") { const response = await fetch("/api/growth-engine/learning/ideas", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ sourcePatternKey, action }) }); if (!response.ok) { const body = await response.json(); setError(body.error || "Idea Candidateの更新に失敗しました。"); return; } await refresh(); }
  const summary = data.summary; const patterns = data.patterns;
  return <main className="min-h-screen bg-[#f5f0e8] px-5 py-8 text-[#20241f]"><div className="mx-auto max-w-7xl"><Link className="text-sm font-semibold text-[#596d51]" href="/admin/growth">Growth Engineへ戻る</Link><header className="mt-5 border-b border-[#d7cabc] pb-6"><p className="text-sm font-semibold uppercase text-[#6c5f3d]">Evidence-derived read-only view</p><h1 className="mt-2 text-4xl font-semibold">Learning Patterns</h1><p className="mt-3 text-[#5e625c]">実験結果とEvidenceから導出した傾向です。推薦とIdea Candidateは人間確認後に保存できます。実行操作はありません。</p></header>{error ? <p className="mt-5 rounded border border-red-300 bg-red-50 p-4 text-sm text-red-700">{error}</p> : null}<section className="mt-8 grid gap-4 md:grid-cols-3"><Summary title="Patterns" value={String(summary.patternCount || 0)} /><Summary title="Recommendations" value={String(summary.recommendationCount || 0)} /><Summary title="Idea Candidates" value={String(data.candidates.length)} /></section><section className="mt-8 grid gap-4">{data.recommendations.map((item) => <RecommendationCard key={`${item.patternKey}-${item.stateFingerprint}`} item={item} onReview={review} />)}{!data.recommendations.length ? <p className="rounded border border-[#d7cabc] bg-[#fffaf2] p-5 text-sm text-[#5e625c]">Recommendation対象のEvidence-backed Patternはまだありません。</p> : null}</section><section className="mt-8"><h2 className="text-2xl font-semibold">SNS Idea Candidates</h2><p className="mt-2 text-sm text-[#5e625c]">Recommendationから派生した企画候補です。動画生成・投稿・Experiment作成は行いません。</p><div className="mt-4 grid gap-4">{data.candidates.map((item) => <IdeaCard key={`${item.sourcePatternKey}-${item.stateFingerprint}`} item={item} onReview={reviewIdea} />)}{!data.candidates.length ? <p className="rounded border border-[#d7cabc] bg-[#fffaf2] p-5 text-sm text-[#5e625c]">Idea Candidateはまだありません。</p> : null}</div></section><details className="mt-8"><summary className="cursor-pointer font-semibold">Pattern詳細</summary><section className="mt-4 grid gap-4">{patterns.map((pattern) => <article key={pattern.patternKey} className="rounded border border-[#d7cabc] bg-[#fffaf2] p-5"><p className="text-xs font-semibold uppercase text-[#6c5f3d]">{pattern.resultClass} / {pattern.maturity} / confidence {pattern.confidence}</p><p className="mt-2 text-sm">{pattern.scope.metric} / {pattern.scope.platform} / sample {pattern.sampleSize} / decay {pattern.decayScore}</p><p className="mt-2 text-sm text-[#5e625c]">Evidence {pattern.sourceEvidenceCount} source / {pattern.claimCount} claims / 不足: {pattern.missingEvidence.join(", ") || "なし"}</p></article>)}</section></details></div></main>;
}
function Summary({ title, value }: { title: string; value: string }) { return <div className="rounded border border-[#d7cabc] bg-[#fffaf2] p-5"><p className="text-sm font-semibold uppercase text-[#6c5f3d]">{title}</p><p className="mt-2 text-xl font-semibold">{value}</p></div>; }

type Recommendation = { patternKey: string; recommendationType: string; priority: number; primaryGoal: string; reason: string; scope: Record<string, string>; traceability: { supportingEvidence: Array<{ sourceId: string; claimIds: string[] }>; missingEvidence: string[]; experimentCount: number; sampleSize: number; confidence: number; maturity: string; lastTestedAt: string | null; decayScore: number }; status: string; stateFingerprint: string };
function RecommendationCard({ item, onReview }: { item: Recommendation; onReview: (patternKey: string, action: "save" | "dismiss") => Promise<void> }) { return <article className="rounded border border-[#d7cabc] bg-[#fffaf2] p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-semibold uppercase text-[#6c5f3d]">{item.recommendationType} / {item.primaryGoal}</p><h2 className="mt-1 font-semibold">Priority {item.priority} / {item.status}</h2></div><div className="flex gap-2"><button className="rounded border border-[#596d51] bg-white px-3 py-2 text-sm font-semibold text-[#596d51]" onClick={() => void onReview(item.patternKey, "save")}>Save</button><button className="rounded border border-[#9a5c52] bg-white px-3 py-2 text-sm font-semibold text-[#9a5c52]" onClick={() => void onReview(item.patternKey, "dismiss")}>Dismiss</button></div></div><p className="mt-3 text-sm leading-6">{item.reason}</p><p className="mt-2 text-sm text-[#5e625c]">Scope: {Object.entries(item.scope).map(([key, value]) => `${key}=${value}`).join(" / ")}</p><p className="mt-2 text-sm text-[#5e625c]">Evidence: {item.traceability.supportingEvidence.map((evidence) => `${evidence.sourceId} [${evidence.claimIds.join(", ")}]`).join("; ") || "なし"}</p><p className="mt-2 text-sm text-[#5e625c]">実験 {item.traceability.experimentCount} / sample {item.traceability.sampleSize} / confidence {item.traceability.confidence} / maturity {item.traceability.maturity} / decay {item.traceability.decayScore}</p><p className="mt-2 text-sm text-[#5e625c]">不足: {item.traceability.missingEvidence.join(", ") || "なし"}</p></article>; }

type IdeaCandidate = { sourceRecommendationId: string; sourcePatternKey: string; stateFingerprint: string; recommendationType: string; primaryGoal: string; title: string; category: string; topic: string; hookStyle: string; cta: string; template: string; character: string; platform: string; locale: string; novelty: number; confidence: number; maturity: string; reason: string; supportingEvidence: Array<{ sourceId: string; claimIds: string[] }>; missingEvidence: string[]; variation: { changed: string[]; reason: string }; experimentability: { whatToTest: string[]; targetMetric: string }; status: string };
function IdeaCard({ item, onReview }: { item: IdeaCandidate; onReview: (patternKey: string, action: "save" | "dismiss") => Promise<void> }) { return <article className="rounded border border-[#b8c7b0] bg-white p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-semibold uppercase text-[#596d51]">{item.recommendationType} / {item.primaryGoal} / {item.status}</p><h3 className="mt-1 text-lg font-semibold">{item.title}</h3></div><div className="flex gap-2"><button className="rounded border border-[#596d51] px-3 py-2 text-sm font-semibold text-[#596d51]" onClick={() => void onReview(item.sourcePatternKey, "save")}>Save</button><button className="rounded border border-[#9a5c52] px-3 py-2 text-sm font-semibold text-[#9a5c52]" onClick={() => void onReview(item.sourcePatternKey, "dismiss")}>Dismiss</button></div></div><p className="mt-3 text-sm">{item.topic} / {item.hookStyle} / {item.cta} / {item.template}</p><p className="mt-2 text-sm text-[#5e625c]">character={item.character} / platform={item.platform} / locale={item.locale} / novelty={item.novelty} / confidence={item.confidence} / maturity={item.maturity}</p><p className="mt-2 text-sm text-[#5e625c]">What to test: {item.experimentability.whatToTest.join(", ")} / variation: {item.variation.reason}</p><p className="mt-2 text-sm text-[#5e625c]">Reason: {item.reason}</p><p className="mt-2 text-sm text-[#5e625c]">Evidence: {item.supportingEvidence.map((evidence) => `${evidence.sourceId} [${evidence.claimIds.join(", ")}]`).join("; ") || "なし"}</p><p className="mt-2 text-sm text-[#5e625c]">不足: {item.missingEvidence.join(", ") || "なし"}</p></article>; }
