import { env } from "cloudflare:workers";
import { getAdminSession, adminEmail } from "@/app/lib/google-admin-auth";
import { GROWTH_ENGINE_TENANT_ID } from "@/app/lib/growth-engine";
import { listDraftRenderJobs, renderDraftToMp4 } from "@/app/lib/sns-draft-renderer";

async function admin() { const session = await getAdminSession(); return session && session.email.toLowerCase() === adminEmail().toLowerCase(); }
function tenant(value: unknown) { const id = String(value || GROWTH_ENGINE_TENANT_ID); if (id !== GROWTH_ENGINE_TENANT_ID) throw new Error("Invalid tenant_id."); return id; }
export async function GET(request: Request, context: { params: Promise<{ id: string }> }) { if (!(await admin())) return Response.json({ ok: false, error: "Admin authentication required." }, { status: 401 }); try { const url = new URL(request.url); return Response.json({ ok: true, jobs: await listDraftRenderJobs(env.DB, (await context.params).id, tenant(url.searchParams.get("tenantId"))) }, { headers: { "Cache-Control": "no-store" } }); } catch (error) { return Response.json({ ok: false, error: error instanceof Error ? error.message : "Render API failed." }, { status: 400 }); } }
export async function POST(request: Request, context: { params: Promise<{ id: string }> }) { if (!(await admin())) return Response.json({ ok: false, error: "Admin authentication required." }, { status: 401 }); const body = await request.json().catch(() => ({})) as Record<string, unknown>; try { const job = await renderDraftToMp4(env.DB, (await context.params).id, { platform: body.platform ? String(body.platform) : undefined, rerender: body.rerender === true }, tenant(body.tenantId ?? body.tenant_id), env as unknown as Record<string, unknown>); return Response.json({ ok: true, job }); } catch (error) { return Response.json({ ok: false, error: error instanceof Error ? error.message : "Render failed." }, { status: 400 }); } }
