PRAGMA defer_foreign_keys=TRUE;
CREATE TABLE studioos_tenant_metadata (
  tenant_id TEXT PRIMARY KEY,
  tenant_key TEXT NOT NULL UNIQUE,
  guild_id TEXT NOT NULL,
  character_id TEXT NOT NULL,
  market TEXT NOT NULL,
  country TEXT NOT NULL,
  locale TEXT NOT NULL,
  schema_version INTEGER NOT NULL DEFAULT 1,
  environment TEXT NOT NULL,
  legacy_tenant_alias TEXT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
INSERT INTO "studioos_tenant_metadata" ("tenant_id","tenant_key","guild_id","character_id","market","country","locale","schema_version","environment","legacy_tenant_alias","created_at") VALUES('luna-oracle','luna-oracle','raven-guild','luna','jp','JP','ja-JP',1,'production-preparation','luna-starwind','2026-08-26 01:42:36');
CREATE TABLE studioos_member_context (
  member_id TEXT NOT NULL,
  tenant_id TEXT NOT NULL,
  guild_id TEXT NOT NULL,
  character_id TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (member_id, tenant_id),
  FOREIGN KEY (tenant_id) REFERENCES studioos_tenant_metadata(tenant_id)
);
CREATE TABLE analytics_events (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  tenant_id TEXT NOT NULL,
  event_name TEXT NOT NULL,
  event_namespace TEXT NOT NULL,
  path TEXT,
  session_id TEXT,
  member_id TEXT,
  payload_json TEXT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (tenant_id) REFERENCES studioos_tenant_metadata(tenant_id)
);
INSERT INTO "analytics_events" ("id","tenant_id","event_name","event_namespace","path","session_id","member_id","payload_json","created_at") VALUES(1,'luna-oracle','ai_reading_start','legacy-luna','/ai-reading',NULL,NULL,'{"id":"e8564ce0-3d62-4259-a97f-0b3b6c607add","created_at":"2026-08-13 20:21:26","tenant_id":"luna-starwind","event_name":"ai_reading_start","page_path":"/ai-reading","page_title":"AI鑑定","referrer":"","referrer_host":"","source":"","medium":"","campaign":"","link_url":"","link_text":"","visitor_hash":"88ff6d83b1e4428a8ad46ceffa25e4bf2bebd784874e3721b6a368612efebd24","user_agent":"curl/8.21.0"}','2026-08-13 20:21:26');
INSERT INTO "analytics_events" ("id","tenant_id","event_name","event_namespace","path","session_id","member_id","payload_json","created_at") VALUES(2,'luna-oracle','ai_reading_start','legacy-luna','/ai-reading',NULL,NULL,'{"id":"a56bc8e5-d565-4e3a-8d89-ebee6f801e0d","created_at":"2026-08-13 20:21:46","tenant_id":"luna-starwind","event_name":"ai_reading_start","page_path":"/ai-reading","page_title":"AI鑑定","referrer":"","referrer_host":"","source":"","medium":"","campaign":"","link_url":"","link_text":"","visitor_hash":"88ff6d83b1e4428a8ad46ceffa25e4bf2bebd784874e3721b6a368612efebd24","user_agent":"curl/8.21.0"}','2026-08-13 20:21:46');
INSERT INTO "analytics_events" ("id","tenant_id","event_name","event_namespace","path","session_id","member_id","payload_json","created_at") VALUES(3,'luna-oracle','ai_reading_start','legacy-luna','/ai-reading',NULL,NULL,'{"id":"5434220c-07cb-4caf-bfad-62121fc15c49","created_at":"2026-08-13 20:21:58","tenant_id":"luna-starwind","event_name":"ai_reading_start","page_path":"/ai-reading","page_title":"AI鑑定","referrer":"","referrer_host":"","source":"","medium":"","campaign":"","link_url":"","link_text":"","visitor_hash":"88ff6d83b1e4428a8ad46ceffa25e4bf2bebd784874e3721b6a368612efebd24","user_agent":"curl/8.21.0"}','2026-08-13 20:21:58');
INSERT INTO "analytics_events" ("id","tenant_id","event_name","event_namespace","path","session_id","member_id","payload_json","created_at") VALUES(4,'luna-oracle','review_check','legacy-luna','/',NULL,NULL,'{"id":"14805c38-6d07-4f78-9ea8-076e265c2d48","created_at":"2026-08-15 09:29:02","tenant_id":"luna-starwind","event_name":"review_check","page_path":"/","page_title":"review","referrer":"","referrer_host":"","source":"","medium":"","campaign":"","link_url":"","link_text":"","visitor_hash":"68bf73b44a92bbe2cebd7eb620b643bb1a801c1e9be565ba6501dbfcc12a0118","user_agent":"curl/8.21.0"}','2026-08-15 09:29:02');
INSERT INTO "analytics_events" ("id","tenant_id","event_name","event_namespace","path","session_id","member_id","payload_json","created_at") VALUES(5,'luna-oracle','perfect_analytics_check','legacy-luna','/',NULL,NULL,'{"id":"2e3ef99e-0aa9-421a-b7be-cf31fcdb9e82","created_at":"2026-08-15 10:01:22","tenant_id":"luna-starwind","event_name":"perfect_analytics_check","page_path":"/","page_title":"analytics-perfect","referrer":"","referrer_host":"","source":"","medium":"","campaign":"","link_url":"","link_text":"","visitor_hash":"68bf73b44a92bbe2cebd7eb620b643bb1a801c1e9be565ba6501dbfcc12a0118","user_agent":"curl/8.21.0"}','2026-08-15 10:01:22');
INSERT INTO "analytics_events" ("id","tenant_id","event_name","event_namespace","path","session_id","member_id","payload_json","created_at") VALUES(6,'luna-oracle','page_view','legacy-luna','/admin/analytics',NULL,NULL,'{"id":"bc14bd53-ed56-4b75-94df-e3c596912e85","created_at":"2026-08-15 14:15:45","tenant_id":"luna-starwind","event_name":"page_view","page_path":"/admin/analytics","page_title":"??????","referrer":"","referrer_host":"","source":"","medium":"","campaign":"","link_url":"","link_text":"","visitor_hash":"13f2cc2f1552126e4636c07a2b4b5f3873a89c08caf6a5b4e371985bd81d61c1","user_agent":"Mozilla/5.0 (Windows NT; Windows NT 10.0; ja-JP) WindowsPowerShell/5.1.26100.9168"}','2026-08-15 14:15:45');
INSERT INTO "analytics_events" ("id","tenant_id","event_name","event_namespace","path","session_id","member_id","payload_json","created_at") VALUES(7,'luna-oracle','page_view','legacy-luna','/profile',NULL,NULL,'{"id":"adccde02-4271-451c-b79e-925339c2ca07","created_at":"2026-08-16 11:15:58","tenant_id":"luna-starwind","event_name":"page_view","page_path":"/profile","page_title":"ルナについて | Luna Starwind","referrer":"","referrer_host":"","source":"","medium":"","campaign":"","link_url":"","link_text":"","visitor_hash":"7f2edb41dfae6ec8ac729a50f3fb9865e235213459ade0080b243f75851b719e","user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/145.0.0.0 Safari/537.36 (compatible; meta-externalagent/1.1 (+https://developers.facebook.com/docs/sharing/webmasters/crawler))"}','2026-08-16 11:15:58');
INSERT INTO "analytics_events" ("id","tenant_id","event_name","event_namespace","path","session_id","member_id","payload_json","created_at") VALUES(8,'luna-oracle','page_view','legacy-luna','/privacy',NULL,NULL,'{"id":"66e060b8-8e0b-4ec7-8f9c-5b6791c09318","created_at":"2026-08-16 11:58:40","tenant_id":"luna-starwind","event_name":"page_view","page_path":"/privacy","page_title":"プライバシーポリシー | Luna Starwind","referrer":"","referrer_host":"","source":"","medium":"","campaign":"","link_url":"","link_text":"","visitor_hash":"c92377237590b832a6d3cb0e91f5efca781c1dead82dc31c68714f83dc7db05f","user_agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/145.0.0.0 Safari/537.36 (compatible; meta-externalagent/1.1 (+https://developers.facebook.com/docs/sharing/webmasters/crawler))"}','2026-08-16 11:58:40');
INSERT INTO "analytics_events" ("id","tenant_id","event_name","event_namespace","path","session_id","member_id","payload_json","created_at") VALUES(9,'luna-oracle','page_view','legacy-luna','/first',NULL,NULL,'{"id":"e8e3a55e-75be-481c-b0e7-0275c0c9aff2","created_at":"2026-08-16 12:09:17","tenant_id":"luna-starwind","event_name":"page_view","page_path":"/first","page_title":"Luna Starwind | 恋愛と人間関係をやさしく整えるオンライン鑑定","referrer":"","referrer_host":"","source":"","medium":"","campaign":"","link_url":"","link_text":"","visitor_hash":"fc26a0435cf8f5122098bc44906c23e458f9c0c1e46050e37a2e6fc959322c47","user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/145.0.0.0 Safari/537.36 (compatible; meta-externalagent/1.1 (+https://developers.facebook.com/docs/sharing/webmasters/crawler))"}','2026-08-16 12:09:17');
INSERT INTO "analytics_events" ("id","tenant_id","event_name","event_namespace","path","session_id","member_id","payload_json","created_at") VALUES(10,'luna-oracle','page_view','legacy-luna','/operations',NULL,NULL,'{"id":"22bf8f2d-81ad-4224-ac20-6f067c71fa79","created_at":"2026-08-16 13:37:41","tenant_id":"luna-starwind","event_name":"page_view","page_path":"/operations","page_title":"Luna Starwind | 恋愛と人間関係をやさしく整えるオンライン鑑定","referrer":"","referrer_host":"","source":"","medium":"","campaign":"","link_url":"","link_text":"","visitor_hash":"c5c3ecca1680745e9e8d3b27b88f091be19094009526de0cf37c16b59960d5a2","user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/145.0.0.0 Safari/537.36 (compatible; meta-externalagent/1.1 (+https://developers.facebook.com/docs/sharing/webmasters/crawler))"}','2026-08-16 13:37:41');
INSERT INTO "analytics_events" ("id","tenant_id","event_name","event_namespace","path","session_id","member_id","payload_json","created_at") VALUES(11,'luna-oracle','page_view','legacy-luna','/reservation',NULL,NULL,'{"id":"e898cacf-5eda-458f-b8f1-7eea89a67388","created_at":"2026-08-16 14:59:16","tenant_id":"luna-starwind","event_name":"page_view","page_path":"/reservation","page_title":"Luna Starwind | 恋愛と人間関係をやさしく整えるオンライン鑑定","referrer":"","referrer_host":"","source":"","medium":"","campaign":"","link_url":"","link_text":"","visitor_hash":"207a81b42879195296c323df60cec9e7c2ee967311fadbbe13c2e068b9ef10ec","user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/145.0.0.0 Safari/537.36 (compatible; meta-externalagent/1.1 (+https://developers.facebook.com/docs/sharing/webmasters/crawler))"}','2026-08-16 14:59:16');
INSERT INTO "analytics_events" ("id","tenant_id","event_name","event_namespace","path","session_id","member_id","payload_json","created_at") VALUES(12,'luna-oracle','page_view','legacy-luna','/disclaimer',NULL,NULL,'{"id":"137c4564-52dc-4e36-a6ef-5030b9b8237e","created_at":"2026-08-16 16:07:57","tenant_id":"luna-starwind","event_name":"page_view","page_path":"/disclaimer","page_title":"免責事項 | Luna Starwind","referrer":"","referrer_host":"","source":"","medium":"","campaign":"","link_url":"","link_text":"","visitor_hash":"8d66be20231d1e4b3dce3ce0b700dc7c7e209e9b906238e04efc3ee25103287d","user_agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/145.0.0.0 Safari/537.36 (compatible; meta-externalagent/1.1 (+https://developers.facebook.com/docs/sharing/webmasters/crawler))"}','2026-08-16 16:07:57');
INSERT INTO "analytics_events" ("id","tenant_id","event_name","event_namespace","path","session_id","member_id","payload_json","created_at") VALUES(13,'luna-oracle','page_view','legacy-luna','/analytics',NULL,NULL,'{"id":"d44fba55-3199-44cb-bce1-6c8594418185","created_at":"2026-08-16 16:47:53","tenant_id":"luna-starwind","event_name":"page_view","page_path":"/analytics","page_title":"Luna Starwind | 恋愛と人間関係をやさしく整えるオンライン鑑定","referrer":"","referrer_host":"","source":"","medium":"","campaign":"","link_url":"","link_text":"","visitor_hash":"c05f064efd1eddf730ee603eae814f75e751293f8117271163f7acf6b5628009","user_agent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/145.0.0.0 Safari/537.36 (compatible; meta-externalagent/1.1 (+https://developers.facebook.com/docs/sharing/webmasters/crawler))"}','2026-08-16 16:47:53');
INSERT INTO "analytics_events" ("id","tenant_id","event_name","event_namespace","path","session_id","member_id","payload_json","created_at") VALUES(14,'luna-oracle','page_view','legacy-luna','/line',NULL,NULL,'{"id":"512750e9-1658-4f1f-8fd3-44f0e16695cb","created_at":"2026-08-16 16:54:34","tenant_id":"luna-starwind","event_name":"page_view","page_path":"/line","page_title":"Luna Starwind | 恋愛と人間関係をやさしく整えるオンライン鑑定","referrer":"","referrer_host":"","source":"","medium":"","campaign":"","link_url":"","link_text":"","visitor_hash":"ded229ea677a907ac2a0c6d6ec0518f7041c2f299929a5c61cde0436486ed10a","user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/145.0.0.0 Safari/537.36 (compatible; meta-externalagent/1.1 (+https://developers.facebook.com/docs/sharing/webmasters/crawler))"}','2026-08-16 16:54:34');
INSERT INTO "analytics_events" ("id","tenant_id","event_name","event_namespace","path","session_id","member_id","payload_json","created_at") VALUES(15,'luna-oracle','page_view','legacy-luna','/menus',NULL,NULL,'{"id":"c8dc47f1-979f-415a-a357-61761ddfb28f","created_at":"2026-08-16 18:03:19","tenant_id":"luna-starwind","event_name":"page_view","page_path":"/menus","page_title":"鑑定メニュー | Luna Starwind","referrer":"","referrer_host":"","source":"","medium":"","campaign":"","link_url":"","link_text":"","visitor_hash":"cae085723360b434d4b388056949a30ca1805312e69e7aaad902f190d88e27b7","user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/145.0.0.0 Safari/537.36 (compatible; meta-externalagent/1.1 (+https://developers.facebook.com/docs/sharing/webmasters/crawler))"}','2026-08-16 18:03:19');
INSERT INTO "analytics_events" ("id","tenant_id","event_name","event_namespace","path","session_id","member_id","payload_json","created_at") VALUES(16,'luna-oracle','page_view','legacy-luna','/crm',NULL,NULL,'{"id":"76aff599-44d3-4456-9906-f5fecf86098e","created_at":"2026-08-16 18:21:09","tenant_id":"luna-starwind","event_name":"page_view","page_path":"/crm","page_title":"Luna Starwind | 恋愛と人間関係をやさしく整えるオンライン鑑定","referrer":"","referrer_host":"","source":"","medium":"","campaign":"","link_url":"","link_text":"","visitor_hash":"7e7818bac364f619ed13484da6afaede499ba18312f6c968b6819b3d87d4de2a","user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/145.0.0.0 Safari/537.36 (compatible; meta-externalagent/1.1 (+https://developers.facebook.com/docs/sharing/webmasters/crawler))"}','2026-08-16 18:21:09');
INSERT INTO "analytics_events" ("id","tenant_id","event_name","event_namespace","path","session_id","member_id","payload_json","created_at") VALUES(17,'luna-oracle','page_view','legacy-luna','/faq',NULL,NULL,'{"id":"5242f272-ef01-4a16-a59f-69d61301db34","created_at":"2026-08-16 18:37:32","tenant_id":"luna-starwind","event_name":"page_view","page_path":"/faq","page_title":"Luna Starwind | 恋愛と人間関係をやさしく整えるオンライン鑑定","referrer":"","referrer_host":"","source":"","medium":"","campaign":"","link_url":"","link_text":"","visitor_hash":"9e5b913225c2a894dd33d68c3c6d7f6e0cd9cde51f361cede66421fbc125b122","user_agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/145.0.0.0 Safari/537.36 (compatible; meta-externalagent/1.1 (+https://developers.facebook.com/docs/sharing/webmasters/crawler))"}','2026-08-16 18:37:32');
INSERT INTO "analytics_events" ("id","tenant_id","event_name","event_namespace","path","session_id","member_id","payload_json","created_at") VALUES(18,'luna-oracle','page_view','legacy-luna','/',NULL,NULL,'{"id":"dc1e3056-410f-4c47-963a-0b3f43cd5016","created_at":"2026-08-17 07:06:39","tenant_id":"luna-starwind","event_name":"page_view","page_path":"/","page_title":"Luna Starwind | 恋愛と人間関係をやさしく整えるオンライン鑑定","referrer":"https://www.google.com/","referrer_host":"www.google.com","source":"","medium":"","campaign":"","link_url":"","link_text":"","visitor_hash":"bac7c45ebe55b098b4b5ff2ba50dc8252629fcbc7d9304312d940cb65ac35511","user_agent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/145.0.0.0 Safari/537.36 (Stripebot/1.0; +https://docs.stripe.com/stripebot-crawler)"}','2026-08-17 07:06:39');
INSERT INTO "analytics_events" ("id","tenant_id","event_name","event_namespace","path","session_id","member_id","payload_json","created_at") VALUES(19,'luna-oracle','ai_reading_start','legacy-luna','/ai-reading',NULL,NULL,'{"id":"646704f5-151d-4601-ac42-455ecc09259f","created_at":"2026-08-17 07:29:51","tenant_id":"luna-starwind","event_name":"ai_reading_start","page_path":"/ai-reading","page_title":"AIテキスト鑑定","referrer":"","referrer_host":"","source":"server","medium":"api","campaign":"恋愛","link_url":"","link_text":"北海道札幌市","visitor_hash":"5b5b637ba871aa86f7c3a7d653e00d563110e58df5c4f566b6d5df920081c70a","user_agent":"curl/8.21.0"}','2026-08-17 07:29:51');
INSERT INTO "analytics_events" ("id","tenant_id","event_name","event_namespace","path","session_id","member_id","payload_json","created_at") VALUES(20,'luna-oracle','ai_reading_complete','legacy-luna','/ai-reading',NULL,NULL,'{"id":"9b9deee7-c067-4767-851e-7ce64624c3d9","created_at":"2026-08-17 07:30:00","tenant_id":"luna-starwind","event_name":"ai_reading_complete","page_path":"/ai-reading","page_title":"AIテキスト鑑定","referrer":"","referrer_host":"","source":"server","medium":"api","campaign":"恋愛","link_url":"","link_text":"北海道札幌市","visitor_hash":"5b5b637ba871aa86f7c3a7d653e00d563110e58df5c4f566b6d5df920081c70a","user_agent":"curl/8.21.0"}','2026-08-17 07:30:00');
INSERT INTO "analytics_events" ("id","tenant_id","event_name","event_namespace","path","session_id","member_id","payload_json","created_at") VALUES(21,'luna-oracle','page_view','legacy-luna','/',NULL,NULL,'{"id":"f05632ea-2986-4730-8201-33e0fb264fe2","created_at":"2026-08-26 10:44:15","tenant_id":"luna-starwind","event_name":"page_view","page_path":"/","page_title":"Luna Starwind | 恋愛と人間関係をやさしく整えるオンライン鑑定","referrer":"","referrer_host":"","source":"","medium":"","campaign":"","link_url":"","link_text":"","visitor_hash":"6c7db2656c2d0480a9f4167a925f207a436edfcdecab2f94510f76a56167b78e","user_agent":"Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm) Chrome/136.0.0.0 Safari/537.36 AppleWebKit/537.36 (KHTML, like Gecko; compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm) Chrome/116.0.1938.76 Safari/537.36"}','2026-08-26 10:44:15');
INSERT INTO "analytics_events" ("id","tenant_id","event_name","event_namespace","path","session_id","member_id","payload_json","created_at") VALUES(22,'luna-oracle','page_view','legacy-luna','/',NULL,NULL,'{"id":"6877eb2f-2602-45af-8843-cb5ce2732d44","created_at":"2026-08-26 11:43:10","tenant_id":"luna-starwind","event_name":"page_view","page_path":"/","page_title":"Luna Starwind | 恋愛と人間関係をやさしく整えるオンライン鑑定","referrer":"https://www.fortunestudios.jp/","referrer_host":"www.fortunestudios.jp","source":"","medium":"","campaign":"","link_url":"","link_text":"","visitor_hash":"17f1b8094cf707a30b184ccb1ed254247f3b8219d4a05e990572a0307921cd3f","user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/151.0.0.0 Safari/537.36"}','2026-08-26 11:43:10');
INSERT INTO "analytics_events" ("id","tenant_id","event_name","event_namespace","path","session_id","member_id","payload_json","created_at") VALUES(23,'luna-oracle','page_view','legacy-luna','/',NULL,NULL,'{"id":"1798d412-a072-45a6-86ef-6a15a1aca9fb","created_at":"2026-08-26 11:43:28","tenant_id":"luna-starwind","event_name":"page_view","page_path":"/","page_title":"Luna Starwind | 恋愛と人間関係をやさしく整えるオンライン鑑定","referrer":"","referrer_host":"","source":"","medium":"","campaign":"","link_url":"","link_text":"","visitor_hash":"17f1b8094cf707a30b184ccb1ed254247f3b8219d4a05e990572a0307921cd3f","user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/151.0.0.0 Safari/537.36"}','2026-08-26 11:43:28');
INSERT INTO "analytics_events" ("id","tenant_id","event_name","event_namespace","path","session_id","member_id","payload_json","created_at") VALUES(24,'luna-oracle','page_view','legacy-luna','/admin',NULL,NULL,'{"id":"057da7fc-2ea2-49d5-b181-ef5f81261e58","created_at":"2026-08-26 11:44:20","tenant_id":"luna-starwind","event_name":"page_view","page_path":"/admin","page_title":"管理画面 | Luna Starwind","referrer":"","referrer_host":"","source":"","medium":"","campaign":"","link_url":"","link_text":"","visitor_hash":"17f1b8094cf707a30b184ccb1ed254247f3b8219d4a05e990572a0307921cd3f","user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/151.0.0.0 Safari/537.36"}','2026-08-26 11:44:20');
INSERT INTO "analytics_events" ("id","tenant_id","event_name","event_namespace","path","session_id","member_id","payload_json","created_at") VALUES(25,'luna-oracle','page_view','legacy-luna','/menus',NULL,NULL,'{"id":"dbe5cf93-c6a5-41c9-9615-03de28fdd896","created_at":"2026-08-26 11:44:30","tenant_id":"luna-starwind","event_name":"page_view","page_path":"/menus","page_title":"鑑定メニュー | Luna Starwind","referrer":"https://luna.fortunestudios.jp/admin","referrer_host":"luna.fortunestudios.jp","source":"","medium":"","campaign":"","link_url":"","link_text":"","visitor_hash":"17f1b8094cf707a30b184ccb1ed254247f3b8219d4a05e990572a0307921cd3f","user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/151.0.0.0 Safari/537.36"}','2026-08-26 11:44:30');
INSERT INTO "analytics_events" ("id","tenant_id","event_name","event_namespace","path","session_id","member_id","payload_json","created_at") VALUES(26,'luna-oracle','page_view','legacy-luna','/admin/analytics',NULL,NULL,'{"id":"6e2bd356-78b0-4c4e-8374-8c19824eb56e","created_at":"2026-08-26 11:44:59","tenant_id":"luna-starwind","event_name":"page_view","page_path":"/admin/analytics","page_title":"アクセス解析 | Luna Starwind","referrer":"https://luna.fortunestudios.jp/admin","referrer_host":"luna.fortunestudios.jp","source":"","medium":"","campaign":"","link_url":"","link_text":"","visitor_hash":"17f1b8094cf707a30b184ccb1ed254247f3b8219d4a05e990572a0307921cd3f","user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/151.0.0.0 Safari/537.36"}','2026-08-26 11:44:59');
INSERT INTO "analytics_events" ("id","tenant_id","event_name","event_namespace","path","session_id","member_id","payload_json","created_at") VALUES(27,'luna-oracle','page_view','legacy-luna','/admin/blog',NULL,NULL,'{"id":"2a3c8435-785b-4982-a70e-5363c039771b","created_at":"2026-08-26 11:45:37","tenant_id":"luna-starwind","event_name":"page_view","page_path":"/admin/blog","page_title":"Blog Engine | Luna Starwind","referrer":"https://luna.fortunestudios.jp/admin","referrer_host":"luna.fortunestudios.jp","source":"","medium":"","campaign":"","link_url":"","link_text":"","visitor_hash":"17f1b8094cf707a30b184ccb1ed254247f3b8219d4a05e990572a0307921cd3f","user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/151.0.0.0 Safari/537.36"}','2026-08-26 11:45:37');
INSERT INTO "analytics_events" ("id","tenant_id","event_name","event_namespace","path","session_id","member_id","payload_json","created_at") VALUES(28,'luna-oracle','page_view','legacy-luna','/blog/todays-fortune-2026-08-25',NULL,NULL,'{"id":"0a0e30c8-71d0-434a-b0f4-c1769ef153d6","created_at":"2026-08-26 11:46:17","tenant_id":"luna-starwind","event_name":"page_view","page_path":"/blog/todays-fortune-2026-08-25","page_title":"ブログ記事 | Luna Starwind","referrer":"https://luna.fortunestudios.jp/admin/blog","referrer_host":"luna.fortunestudios.jp","source":"","medium":"","campaign":"","link_url":"","link_text":"","visitor_hash":"17f1b8094cf707a30b184ccb1ed254247f3b8219d4a05e990572a0307921cd3f","user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/151.0.0.0 Safari/537.36"}','2026-08-26 11:46:17');
INSERT INTO "analytics_events" ("id","tenant_id","event_name","event_namespace","path","session_id","member_id","payload_json","created_at") VALUES(29,'luna-oracle','article_engaged','legacy-luna','/blog/todays-fortune-2026-08-25',NULL,NULL,'{"id":"ad4c23f0-6009-49fb-bdd6-a1b8975856ff","created_at":"2026-08-26 11:46:17","tenant_id":"luna-starwind","event_name":"article_engaged","page_path":"/blog/todays-fortune-2026-08-25","page_title":"ブログ記事 | Luna Starwind","referrer":"https://luna.fortunestudios.jp/admin/blog","referrer_host":"luna.fortunestudios.jp","source":"","medium":"","campaign":"","link_url":"","link_text":"","visitor_hash":"17f1b8094cf707a30b184ccb1ed254247f3b8219d4a05e990572a0307921cd3f","user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/151.0.0.0 Safari/537.36"}','2026-08-26 11:46:17');
INSERT INTO "analytics_events" ("id","tenant_id","event_name","event_namespace","path","session_id","member_id","payload_json","created_at") VALUES(30,'luna-oracle','page_view','legacy-luna','/blog',NULL,NULL,'{"id":"6bf43e9f-43bc-4a1f-84ca-5b458a7906ab","created_at":"2026-08-26 11:46:39","tenant_id":"luna-starwind","event_name":"page_view","page_path":"/blog","page_title":"ルナの星読みブログ | Luna Starwind","referrer":"https://luna.fortunestudios.jp/blog/todays-fortune-2026-08-25","referrer_host":"luna.fortunestudios.jp","source":"","medium":"","campaign":"","link_url":"","link_text":"","visitor_hash":"17f1b8094cf707a30b184ccb1ed254247f3b8219d4a05e990572a0307921cd3f","user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/151.0.0.0 Safari/537.36"}','2026-08-26 11:46:39');
INSERT INTO "analytics_events" ("id","tenant_id","event_name","event_namespace","path","session_id","member_id","payload_json","created_at") VALUES(31,'luna-oracle','page_view','legacy-luna','/profile',NULL,NULL,'{"id":"ac16ece0-90b3-425f-8aaa-2bfb94fcd537","created_at":"2026-08-26 11:47:17","tenant_id":"luna-starwind","event_name":"page_view","page_path":"/profile","page_title":"ルナについて | Luna Starwind","referrer":"https://luna.fortunestudios.jp/blog/todays-fortune-2026-08-25","referrer_host":"luna.fortunestudios.jp","source":"","medium":"","campaign":"","link_url":"","link_text":"","visitor_hash":"17f1b8094cf707a30b184ccb1ed254247f3b8219d4a05e990572a0307921cd3f","user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/151.0.0.0 Safari/537.36"}','2026-08-26 11:47:17');
INSERT INTO "analytics_events" ("id","tenant_id","event_name","event_namespace","path","session_id","member_id","payload_json","created_at") VALUES(32,'luna-oracle','page_view','legacy-luna','/divination',NULL,NULL,'{"id":"d18a0894-aa4f-4e04-9672-b23764c3ae64","created_at":"2026-08-26 11:47:38","tenant_id":"luna-starwind","event_name":"page_view","page_path":"/divination","page_title":"ルナの占術 | Luna Starwind","referrer":"https://luna.fortunestudios.jp/profile","referrer_host":"luna.fortunestudios.jp","source":"","medium":"","campaign":"","link_url":"","link_text":"","visitor_hash":"17f1b8094cf707a30b184ccb1ed254247f3b8219d4a05e990572a0307921cd3f","user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/151.0.0.0 Safari/537.36"}','2026-08-26 11:47:38');
INSERT INTO "analytics_events" ("id","tenant_id","event_name","event_namespace","path","session_id","member_id","payload_json","created_at") VALUES(33,'luna-oracle','page_view','legacy-luna','/blog',NULL,NULL,'{"id":"e7f97aa4-7110-4316-8d29-614d8274f934","created_at":"2026-08-26 11:48:21","tenant_id":"luna-starwind","event_name":"page_view","page_path":"/blog","page_title":"ルナの星読みブログ | Luna Starwind","referrer":"https://luna.fortunestudios.jp/divination","referrer_host":"luna.fortunestudios.jp","source":"","medium":"","campaign":"","link_url":"","link_text":"","visitor_hash":"17f1b8094cf707a30b184ccb1ed254247f3b8219d4a05e990572a0307921cd3f","user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/151.0.0.0 Safari/537.36"}','2026-08-26 11:48:21');
CREATE TABLE blog_engine_settings (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  tenant_id TEXT NOT NULL UNIQUE,
  enabled INTEGER NOT NULL DEFAULT 1,
  default_author TEXT,
  default_locale TEXT,
  public_base_url TEXT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (tenant_id) REFERENCES studioos_tenant_metadata(tenant_id)
);
INSERT INTO "blog_engine_settings" ("id","tenant_id","enabled","default_author","default_locale","public_base_url","created_at") VALUES(1,'luna-oracle',1,NULL,'ja-JP',NULL,'2026-08-15 19:41:31');
CREATE TABLE blog_engine_articles (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  tenant_id TEXT NOT NULL,
  slug TEXT NOT NULL,
  title TEXT NOT NULL,
  body TEXT,
  locale TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'draft',
  published_at TEXT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (tenant_id, slug),
  FOREIGN KEY (tenant_id) REFERENCES studioos_tenant_metadata(tenant_id)
);
INSERT INTO "blog_engine_articles" ("id","tenant_id","slug","title","body","locale","status","published_at","created_at") VALUES(1,'luna-oracle','fukuen-moon-saturn','復縁で月と土星を見る理由｜ルナのホロスコープ読み',replace('## 復縁で月と土星を見る理由を読む前に\n\nうん、ここは少し丁寧に見たいところだよ。占いに慣れている人ほど、ひとつの天体だけで結論を急がないはず。ルナはまずネイタルチャート全体を見て、ASC、MC、ハウス、主要アスペクト、そして相談内容に関係する天体を順番に絞ります。\n\n## 見る天体と判断順\n\n基本は太陽、月、水星、金星、火星、木星、土星です。恋愛なら金星と火星だけでなく、月の安心感、水星の言葉、土星の怖さや時間感覚も見ます。相性ではふたりの金星だけでなく、月同士、水星同士、金星と火星、土星が作る距離を重ねます。\n\n## ハウスとアスペクトの扱い\n\nハウスは、悩みがどの生活領域で起きているかを見る場所です。5ハウスならときめき、7ハウスなら一対一の関係、8ハウスなら深い結びつきや不安、12ハウスなら言えない気持ちとして読みます。アスペクトは主要5種を優先し、オーブが狭いもの、相談テーマに直結するもの、ASC/MCに触れるものを重く見ます。\n\n## 相談内容へ戻す\n\nじゃあ、ここがいちばん大事。星の配置は、相談者を縛るためではなく、今どこで苦しくなっているかを見つける地図です。復縁なら未練と愛情を分ける。相性なら良し悪しで切らず、どこで会話がずれるかを見る。片思いなら動く時期より先に、言葉の温度と距離の詰め方を見る。\n\n## よくある誤読\n\n金星が強いから恋愛運が良い、スクエアがあるから相性が悪い、土星があるから終わり、とは読みません。配置は単独で決めつけず、ハウス、支配星、アスペクト、相談内容を重ねます。ヘビーユーザーほど、この重ね方を見ると鑑定の質が分かります。\n\n## ルナの結論\n\n急がなくて大丈夫。復縁で月と土星を見る理由は、星の名前を並べるだけでは読み切れません。チャートの構造を見て、そこから気持ちの流れを読み、最後に今の相談へ戻す。この順番を守ることで、占いがただの断定ではなく、次の一歩を選ぶための道具になります。','\n',char(10)),'ja-JP','published','2026-08-15 19:41:31','2026-08-15 19:41:31');
INSERT INTO "blog_engine_articles" ("id","tenant_id","slug","title","body","locale","status","published_at","created_at") VALUES(2,'luna-oracle','compatibility-venus','相性で金星だけを見ない理由｜ルナのホロスコープ読み',replace('## 相性で金星だけを見ない理由を読む前に\n\nうん、ここは少し丁寧に見たいところだよ。占いに慣れている人ほど、ひとつの天体だけで結論を急がないはず。ルナはまずネイタルチャート全体を見て、ASC、MC、ハウス、主要アスペクト、そして相談内容に関係する天体を順番に絞ります。\n\n## 見る天体と判断順\n\n基本は太陽、月、水星、金星、火星、木星、土星です。恋愛なら金星と火星だけでなく、月の安心感、水星の言葉、土星の怖さや時間感覚も見ます。相性ではふたりの金星だけでなく、月同士、水星同士、金星と火星、土星が作る距離を重ねます。\n\n## ハウスとアスペクトの扱い\n\nハウスは、悩みがどの生活領域で起きているかを見る場所です。5ハウスならときめき、7ハウスなら一対一の関係、8ハウスなら深い結びつきや不安、12ハウスなら言えない気持ちとして読みます。アスペクトは主要5種を優先し、オーブが狭いもの、相談テーマに直結するもの、ASC/MCに触れるものを重く見ます。\n\n## 相談内容へ戻す\n\nじゃあ、ここがいちばん大事。星の配置は、相談者を縛るためではなく、今どこで苦しくなっているかを見つける地図です。復縁なら未練と愛情を分ける。相性なら良し悪しで切らず、どこで会話がずれるかを見る。片思いなら動く時期より先に、言葉の温度と距離の詰め方を見る。\n\n## よくある誤読\n\n金星が強いから恋愛運が良い、スクエアがあるから相性が悪い、土星があるから終わり、とは読みません。配置は単独で決めつけず、ハウス、支配星、アスペクト、相談内容を重ねます。ヘビーユーザーほど、この重ね方を見ると鑑定の質が分かります。\n\n## ルナの結論\n\n急がなくて大丈夫。相性で金星だけを見ない理由は、星の名前を並べるだけでは読み切れません。チャートの構造を見て、そこから気持ちの流れを読み、最後に今の相談へ戻す。この順番を守ることで、占いがただの断定ではなく、次の一歩を選ぶための道具になります。','\n',char(10)),'ja-JP','published','2026-08-15 19:41:31','2026-08-15 19:41:31');
INSERT INTO "blog_engine_articles" ("id","tenant_id","slug","title","body","locale","status","published_at","created_at") VALUES(3,'luna-oracle','latitude-house','高緯度出生地でハウスを補正する理由｜ルナのホロスコープ読み',replace('## 高緯度出生地でハウスを補正する理由を読む前に\n\nうん、ここは少し丁寧に見たいところだよ。占いに慣れている人ほど、ひとつの天体だけで結論を急がないはず。ルナはまずネイタルチャート全体を見て、ASC、MC、ハウス、主要アスペクト、そして相談内容に関係する天体を順番に絞ります。\n\n## 見る天体と判断順\n\n基本は太陽、月、水星、金星、火星、木星、土星です。恋愛なら金星と火星だけでなく、月の安心感、水星の言葉、土星の怖さや時間感覚も見ます。相性ではふたりの金星だけでなく、月同士、水星同士、金星と火星、土星が作る距離を重ねます。\n\n## ハウスとアスペクトの扱い\n\nハウスは、悩みがどの生活領域で起きているかを見る場所です。5ハウスならときめき、7ハウスなら一対一の関係、8ハウスなら深い結びつきや不安、12ハウスなら言えない気持ちとして読みます。アスペクトは主要5種を優先し、オーブが狭いもの、相談テーマに直結するもの、ASC/MCに触れるものを重く見ます。\n\n## 相談内容へ戻す\n\nじゃあ、ここがいちばん大事。星の配置は、相談者を縛るためではなく、今どこで苦しくなっているかを見つける地図です。復縁なら未練と愛情を分ける。相性なら良し悪しで切らず、どこで会話がずれるかを見る。片思いなら動く時期より先に、言葉の温度と距離の詰め方を見る。\n\n## よくある誤読\n\n金星が強いから恋愛運が良い、スクエアがあるから相性が悪い、土星があるから終わり、とは読みません。配置は単独で決めつけず、ハウス、支配星、アスペクト、相談内容を重ねます。ヘビーユーザーほど、この重ね方を見ると鑑定の質が分かります。\n\n## ルナの結論\n\n急がなくて大丈夫。高緯度出生地でハウスを補正する理由は、星の名前を並べるだけでは読み切れません。チャートの構造を見て、そこから気持ちの流れを読み、最後に今の相談へ戻す。この順番を守ることで、占いがただの断定ではなく、次の一歩を選ぶための道具になります。','\n',char(10)),'ja-JP','published','2026-08-15 19:41:31','2026-08-15 19:41:31');
INSERT INTO "blog_engine_articles" ("id","tenant_id","slug","title","body","locale","status","published_at","created_at") VALUES(4,'luna-oracle','todays-fortune-2026-08-16','今日の占い 2026年8月16日｜ルナの星読み',replace('## 今日の星の空気\n\nうん、今日の空気は「急いで答えを出さず、相手の反応を観察する日」。月は乙女座、金星は山羊座、水星は双子座の流れとして見ています。細かい度数は簡易計算だから断定に使わず、感情、言葉、惹かれ方の温度を見る目印にします。\n\n## 恋愛と相性の流れ\n\n恋愛では、月の安心感と金星の好みを先に見ます。今日は大きな決断より、相手の返事の速さ、言葉の柔らかさ、自分の心がふっと緩む瞬間を拾うほうが向いています。相性は良い悪いで切らず、会話のリズムと距離感を調整してね。\n\n## 仕事と人間関係\n\n水星の流れを見ると、説明を短く整えるほど伝わりやすい日です。言い切るより、確認を挟むほうが味方が増えます。小さな約束を守る、時間を少し早めに見る、そういう地味な動きが運を支えます。\n\n## 12星座へのひとこと\n\n- 牡羊座: 安心できる場所を先に作ると、会話がやわらぎます。\n- 牡牛座: 言葉選びが鍵。軽く見えても本音はちゃんと届きます。\n- 双子座: 気持ちの揺れを隠しすぎず、やさしく出して大丈夫。\n- 蟹座: 魅力が表に出やすい日。見せ方を少しだけ整えて。\n- 獅子座: 細かい確認が信頼につながります。焦らず丁寧に。\n- 乙女座: 相手とのバランスを見直すと、次の動きが見えます。\n- 天秤座: 深読みしすぎたら、事実と想像を分けてみて。\n- 蠍座: 少し外へ意識を向けると、停滞した気分が動きます。\n- 射手座: 現実的な一歩が恋の不安を落ち着かせます。\n- 山羊座: いつもと違う角度の言葉が、空気を軽くします。\n- 水瓶座: やさしさを受け取る練習の日。遠慮しすぎなくて大丈夫。\n- 魚座: 勢いはあるけれど、返事は一拍置くと整います。\n\n## 今日のルナから\n\nラッキーアクションは「身の回りの香りを変える」。今日は派手に運を取りに行くより、心の置き場所を整える日だよ。急がなくて大丈夫。星の流れを味方にして、できることからひとつ選んでいこう。','\n',char(10)),'ja-JP','published','2026-08-15 21:22:15','2026-08-15 21:22:15');
INSERT INTO "blog_engine_articles" ("id","tenant_id","slug","title","body","locale","status","published_at","created_at") VALUES(5,'luna-oracle','asc-mc-love','ASCとMCを恋愛相談へ戻す読み方｜ルナのホロスコープ読み',replace('## ASCとMCを恋愛相談へ戻す読み方を読む前に\n\nうん、ここは少し丁寧に見たいところだよ。占いに慣れている人ほど、ひとつの天体だけで結論を急がないはず。ルナはまずネイタルチャート全体を見て、ASC、MC、ハウス、主要アスペクト、そして相談内容に関係する天体を順番に絞ります。\n\n## 見る天体と判断順\n\n基本は太陽、月、水星、金星、火星、木星、土星です。恋愛なら金星と火星だけでなく、月の安心感、水星の言葉、土星の怖さや時間感覚も見ます。相性ではふたりの金星だけでなく、月同士、水星同士、金星と火星、土星が作る距離を重ねます。\n\n## ハウスとアスペクトの扱い\n\nハウスは、悩みがどの生活領域で起きているかを見る場所です。5ハウスならときめき、7ハウスなら一対一の関係、8ハウスなら深い結びつきや不安、12ハウスなら言えない気持ちとして読みます。アスペクトは主要5種を優先し、オーブが狭いもの、相談テーマに直結するもの、ASC/MCに触れるものを重く見ます。\n\n## 相談内容へ戻す\n\nじゃあ、ここがいちばん大事。星の配置は、相談者を縛るためではなく、今どこで苦しくなっているかを見つける地図です。復縁なら未練と愛情を分ける。相性なら良し悪しで切らず、どこで会話がずれるかを見る。片思いなら動く時期より先に、言葉の温度と距離の詰め方を見る。\n\n## よくある誤読\n\n金星が強いから恋愛運が良い、スクエアがあるから相性が悪い、土星があるから終わり、とは読みません。配置は単独で決めつけず、ハウス、支配星、アスペクト、相談内容を重ねます。ヘビーユーザーほど、この重ね方を見ると鑑定の質が分かります。\n\n## ルナの結論\n\n急がなくて大丈夫。ASCとMCを恋愛相談へ戻す読み方は、星の名前を並べるだけでは読み切れません。チャートの構造を見て、そこから気持ちの流れを読み、最後に今の相談へ戻す。この順番を守ることで、占いがただの断定ではなく、次の一歩を選ぶための道具になります。','\n',char(10)),'ja-JP','published','2026-08-16 08:00:12','2026-08-16 04:00:13');
INSERT INTO "blog_engine_articles" ("id","tenant_id","slug","title","body","locale","status","published_at","created_at") VALUES(6,'luna-oracle','todays-fortune-2026-08-17','今日の占い 2026年8月17日｜ルナの星読み',replace('## 今日の星の空気\n\nうん、今日の空気は「気持ちを整えてから言葉を選ぶ日」。月は天秤座、金星は山羊座、水星は双子座の流れとして見ています。細かい度数は簡易計算だから断定に使わず、感情、言葉、惹かれ方の温度を見る目印にします。\n\n## 恋愛と相性の流れ\n\n恋愛では、月の安心感と金星の好みを先に見ます。今日は大きな決断より、相手の返事の速さ、言葉の柔らかさ、自分の心がふっと緩む瞬間を拾うほうが向いています。相性は良い悪いで切らず、会話のリズムと距離感を調整してね。\n\n## 仕事と人間関係\n\n水星の流れを見ると、説明を短く整えるほど伝わりやすい日です。言い切るより、確認を挟むほうが味方が増えます。小さな約束を守る、時間を少し早めに見る、そういう地味な動きが運を支えます。\n\n## 12星座へのひとこと\n\n- 牡羊座: 言葉選びが鍵。軽く見えても本音はちゃんと届きます。\n- 牡牛座: 気持ちの揺れを隠しすぎず、やさしく出して大丈夫。\n- 双子座: 魅力が表に出やすい日。見せ方を少しだけ整えて。\n- 蟹座: 細かい確認が信頼につながります。焦らず丁寧に。\n- 獅子座: 相手とのバランスを見直すと、次の動きが見えます。\n- 乙女座: 深読みしすぎたら、事実と想像を分けてみて。\n- 天秤座: 少し外へ意識を向けると、停滞した気分が動きます。\n- 蠍座: 現実的な一歩が恋の不安を落ち着かせます。\n- 射手座: いつもと違う角度の言葉が、空気を軽くします。\n- 山羊座: やさしさを受け取る練習の日。遠慮しすぎなくて大丈夫。\n- 水瓶座: 勢いはあるけれど、返事は一拍置くと整います。\n- 魚座: 安心できる場所を先に作ると、会話がやわらぎます。\n\n## 今日のルナから\n\nラッキーアクションは「気になっていた予定をひとつ整理する」。今日は派手に運を取りに行くより、心の置き場所を整える日だよ。急がなくて大丈夫。星の流れを味方にして、できることからひとつ選んでいこう。','\n',char(10)),'ja-JP','published','2026-08-16 22:00:12','2026-08-16 22:00:12');
INSERT INTO "blog_engine_articles" ("id","tenant_id","slug","title","body","locale","status","published_at","created_at") VALUES(7,'luna-oracle','square','スクエアを悪い配置と決めつけない理由｜ルナのホロスコープ読み',replace('## スクエアを悪い配置と決めつけない理由を読む前に\n\nうん、ここは少し丁寧に見たいところだよ。占いに慣れている人ほど、ひとつの天体だけで結論を急がないはず。ルナはまずネイタルチャート全体を見て、ASC、MC、ハウス、主要アスペクト、そして相談内容に関係する天体を順番に絞ります。\n\n## 見る天体と判断順\n\n基本は太陽、月、水星、金星、火星、木星、土星です。恋愛なら金星と火星だけでなく、月の安心感、水星の言葉、土星の怖さや時間感覚も見ます。相性ではふたりの金星だけでなく、月同士、水星同士、金星と火星、土星が作る距離を重ねます。\n\n## ハウスとアスペクトの扱い\n\nハウスは、悩みがどの生活領域で起きているかを見る場所です。5ハウスならときめき、7ハウスなら一対一の関係、8ハウスなら深い結びつきや不安、12ハウスなら言えない気持ちとして読みます。アスペクトは主要5種を優先し、オーブが狭いもの、相談テーマに直結するもの、ASC/MCに触れるものを重く見ます。\n\n## 相談内容へ戻す\n\nじゃあ、ここがいちばん大事。星の配置は、相談者を縛るためではなく、今どこで苦しくなっているかを見つける地図です。復縁なら未練と愛情を分ける。相性なら良し悪しで切らず、どこで会話がずれるかを見る。片思いなら動く時期より先に、言葉の温度と距離の詰め方を見る。\n\n## よくある誤読\n\n金星が強いから恋愛運が良い、スクエアがあるから相性が悪い、土星があるから終わり、とは読みません。配置は単独で決めつけず、ハウス、支配星、アスペクト、相談内容を重ねます。ヘビーユーザーほど、この重ね方を見ると鑑定の質が分かります。\n\n## ルナの結論\n\n急がなくて大丈夫。スクエアを悪い配置と決めつけない理由は、星の名前を並べるだけでは読み切れません。チャートの構造を見て、そこから気持ちの流れを読み、最後に今の相談へ戻す。この順番を守ることで、占いがただの断定ではなく、次の一歩を選ぶための道具になります。','\n',char(10)),'ja-JP','published','2026-08-17 08:00:13','2026-08-17 04:00:12');
INSERT INTO "blog_engine_articles" ("id","tenant_id","slug","title","body","locale","status","published_at","created_at") VALUES(8,'luna-oracle','todays-fortune-2026-08-18','今日の占い 2026年8月18日｜ルナの星読み',replace('## 今日の星の空気\n\nうん、今日の空気は「小さな約束や習慣が関係を支える日」。月は天秤座、金星は山羊座、水星は蟹座の流れとして見ています。細かい度数は簡易計算だから断定に使わず、感情、言葉、惹かれ方の温度を見る目印にします。\n\n## 恋愛と相性の流れ\n\n恋愛では、月の安心感と金星の好みを先に見ます。今日は大きな決断より、相手の返事の速さ、言葉の柔らかさ、自分の心がふっと緩む瞬間を拾うほうが向いています。相性は良い悪いで切らず、会話のリズムと距離感を調整してね。\n\n## 仕事と人間関係\n\n水星の流れを見ると、説明を短く整えるほど伝わりやすい日です。言い切るより、確認を挟むほうが味方が増えます。小さな約束を守る、時間を少し早めに見る、そういう地味な動きが運を支えます。\n\n## 12星座へのひとこと\n\n- 牡羊座: 気持ちの揺れを隠しすぎず、やさしく出して大丈夫。\n- 牡牛座: 魅力が表に出やすい日。見せ方を少しだけ整えて。\n- 双子座: 細かい確認が信頼につながります。焦らず丁寧に。\n- 蟹座: 相手とのバランスを見直すと、次の動きが見えます。\n- 獅子座: 深読みしすぎたら、事実と想像を分けてみて。\n- 乙女座: 少し外へ意識を向けると、停滞した気分が動きます。\n- 天秤座: 現実的な一歩が恋の不安を落ち着かせます。\n- 蠍座: いつもと違う角度の言葉が、空気を軽くします。\n- 射手座: やさしさを受け取る練習の日。遠慮しすぎなくて大丈夫。\n- 山羊座: 勢いはあるけれど、返事は一拍置くと整います。\n- 水瓶座: 安心できる場所を先に作ると、会話がやわらぎます。\n- 魚座: 言葉選びが鍵。軽く見えても本音はちゃんと届きます。\n\n## 今日のルナから\n\nラッキーアクションは「相手のペースを一度尊重する」。今日は派手に運を取りに行くより、心の置き場所を整える日だよ。急がなくて大丈夫。星の流れを味方にして、できることからひとつ選んでいこう。','\n',char(10)),'ja-JP','published','2026-08-17 22:00:11','2026-08-17 22:00:11');
INSERT INTO "blog_engine_articles" ("id","tenant_id","slug","title","body","locale","status","published_at","created_at") VALUES(9,'luna-oracle','kataomoi-mercury-mars','片思いで水星と火星を見る理由｜ルナのホロスコープ読み',replace('## 片思いで水星と火星を見る理由を読む前に\n\nうん、ここは少し丁寧に見たいところだよ。占いに慣れている人ほど、ひとつの天体だけで結論を急がないはず。ルナはまずネイタルチャート全体を見て、ASC、MC、ハウス、主要アスペクト、そして相談内容に関係する天体を順番に絞ります。\n\n## 見る天体と判断順\n\n基本は太陽、月、水星、金星、火星、木星、土星です。恋愛なら金星と火星だけでなく、月の安心感、水星の言葉、土星の怖さや時間感覚も見ます。相性ではふたりの金星だけでなく、月同士、水星同士、金星と火星、土星が作る距離を重ねます。\n\n## ハウスとアスペクトの扱い\n\nハウスは、悩みがどの生活領域で起きているかを見る場所です。5ハウスならときめき、7ハウスなら一対一の関係、8ハウスなら深い結びつきや不安、12ハウスなら言えない気持ちとして読みます。アスペクトは主要5種を優先し、オーブが狭いもの、相談テーマに直結するもの、ASC/MCに触れるものを重く見ます。\n\n## 相談内容へ戻す\n\nじゃあ、ここがいちばん大事。星の配置は、相談者を縛るためではなく、今どこで苦しくなっているかを見つける地図です。復縁なら未練と愛情を分ける。相性なら良し悪しで切らず、どこで会話がずれるかを見る。片思いなら動く時期より先に、言葉の温度と距離の詰め方を見る。\n\n## よくある誤読\n\n金星が強いから恋愛運が良い、スクエアがあるから相性が悪い、土星があるから終わり、とは読みません。配置は単独で決めつけず、ハウス、支配星、アスペクト、相談内容を重ねます。ヘビーユーザーほど、この重ね方を見ると鑑定の質が分かります。\n\n## ルナの結論\n\n急がなくて大丈夫。片思いで水星と火星を見る理由は、星の名前を並べるだけでは読み切れません。チャートの構造を見て、そこから気持ちの流れを読み、最後に今の相談へ戻す。この順番を守ることで、占いがただの断定ではなく、次の一歩を選ぶための道具になります。','\n',char(10)),'ja-JP','published','2026-08-18 08:00:10','2026-08-18 04:00:12');
INSERT INTO "blog_engine_articles" ("id","tenant_id","slug","title","body","locale","status","published_at","created_at") VALUES(10,'luna-oracle','todays-fortune-2026-08-19','今日の占い 2026年8月19日｜ルナの星読み',replace('## 今日の星の空気\n\nうん、今日の空気は「本音と建前の差を責めずに見分ける日」。月は蠍座、金星は山羊座、水星は蟹座の流れとして見ています。細かい度数は簡易計算だから断定に使わず、感情、言葉、惹かれ方の温度を見る目印にします。\n\n## 恋愛と相性の流れ\n\n恋愛では、月の安心感と金星の好みを先に見ます。今日は大きな決断より、相手の返事の速さ、言葉の柔らかさ、自分の心がふっと緩む瞬間を拾うほうが向いています。相性は良い悪いで切らず、会話のリズムと距離感を調整してね。\n\n## 仕事と人間関係\n\n水星の流れを見ると、説明を短く整えるほど伝わりやすい日です。言い切るより、確認を挟むほうが味方が増えます。小さな約束を守る、時間を少し早めに見る、そういう地味な動きが運を支えます。\n\n## 12星座へのひとこと\n\n- 牡羊座: 魅力が表に出やすい日。見せ方を少しだけ整えて。\n- 牡牛座: 細かい確認が信頼につながります。焦らず丁寧に。\n- 双子座: 相手とのバランスを見直すと、次の動きが見えます。\n- 蟹座: 深読みしすぎたら、事実と想像を分けてみて。\n- 獅子座: 少し外へ意識を向けると、停滞した気分が動きます。\n- 乙女座: 現実的な一歩が恋の不安を落ち着かせます。\n- 天秤座: いつもと違う角度の言葉が、空気を軽くします。\n- 蠍座: やさしさを受け取る練習の日。遠慮しすぎなくて大丈夫。\n- 射手座: 勢いはあるけれど、返事は一拍置くと整います。\n- 山羊座: 安心できる場所を先に作ると、会話がやわらぎます。\n- 水瓶座: 言葉選びが鍵。軽く見えても本音はちゃんと届きます。\n- 魚座: 気持ちの揺れを隠しすぎず、やさしく出して大丈夫。\n\n## 今日のルナから\n\nラッキーアクションは「白か淡いピンクを一点だけ入れる」。今日は派手に運を取りに行くより、心の置き場所を整える日だよ。急がなくて大丈夫。星の流れを味方にして、できることからひとつ選んでいこう。','\n',char(10)),'ja-JP','published','2026-08-18 22:00:24','2026-08-18 22:00:24');
INSERT INTO "blog_engine_articles" ("id","tenant_id","slug","title","body","locale","status","published_at","created_at") VALUES(11,'luna-oracle','eighth-house-love','8ハウスが恋愛相談で出るとき｜ルナのホロスコープ読み',replace('## 8ハウスが恋愛相談で出るときを読む前に\n\nうん、ここは少し丁寧に見たいところだよ。占いに慣れている人ほど、ひとつの天体だけで結論を急がないはず。ルナはまずネイタルチャート全体を見て、ASC、MC、ハウス、主要アスペクト、そして相談内容に関係する天体を順番に絞ります。\n\n## 見る天体と判断順\n\n基本は太陽、月、水星、金星、火星、木星、土星です。恋愛なら金星と火星だけでなく、月の安心感、水星の言葉、土星の怖さや時間感覚も見ます。相性ではふたりの金星だけでなく、月同士、水星同士、金星と火星、土星が作る距離を重ねます。\n\n## ハウスとアスペクトの扱い\n\nハウスは、悩みがどの生活領域で起きているかを見る場所です。5ハウスならときめき、7ハウスなら一対一の関係、8ハウスなら深い結びつきや不安、12ハウスなら言えない気持ちとして読みます。アスペクトは主要5種を優先し、オーブが狭いもの、相談テーマに直結するもの、ASC/MCに触れるものを重く見ます。\n\n## 相談内容へ戻す\n\nじゃあ、ここがいちばん大事。星の配置は、相談者を縛るためではなく、今どこで苦しくなっているかを見つける地図です。復縁なら未練と愛情を分ける。相性なら良し悪しで切らず、どこで会話がずれるかを見る。片思いなら動く時期より先に、言葉の温度と距離の詰め方を見る。\n\n## よくある誤読\n\n金星が強いから恋愛運が良い、スクエアがあるから相性が悪い、土星があるから終わり、とは読みません。配置は単独で決めつけず、ハウス、支配星、アスペクト、相談内容を重ねます。ヘビーユーザーほど、この重ね方を見ると鑑定の質が分かります。\n\n## ルナの結論\n\n急がなくて大丈夫。8ハウスが恋愛相談で出るときは、星の名前を並べるだけでは読み切れません。チャートの構造を見て、そこから気持ちの流れを読み、最後に今の相談へ戻す。この順番を守ることで、占いがただの断定ではなく、次の一歩を選ぶための道具になります。','\n',char(10)),'ja-JP','published','2026-08-19 08:00:24','2026-08-19 04:00:25');
INSERT INTO "blog_engine_articles" ("id","tenant_id","slug","title","body","locale","status","published_at","created_at") VALUES(12,'luna-oracle','todays-fortune-2026-08-20','今日の占い 2026年8月20日｜ルナの星読み',replace('## 今日の星の空気\n\nうん、今日の空気は「気持ちを整えてから言葉を選ぶ日」。月は蠍座、金星は山羊座、水星は蟹座の流れとして見ています。細かい度数は簡易計算だから断定に使わず、感情、言葉、惹かれ方の温度を見る目印にします。\n\n## 恋愛と相性の流れ\n\n恋愛では、月の安心感と金星の好みを先に見ます。今日は大きな決断より、相手の返事の速さ、言葉の柔らかさ、自分の心がふっと緩む瞬間を拾うほうが向いています。相性は良い悪いで切らず、会話のリズムと距離感を調整してね。\n\n## 仕事と人間関係\n\n水星の流れを見ると、説明を短く整えるほど伝わりやすい日です。言い切るより、確認を挟むほうが味方が増えます。小さな約束を守る、時間を少し早めに見る、そういう地味な動きが運を支えます。\n\n## 12星座へのひとこと\n\n- 牡羊座: 少し外へ意識を向けると、停滞した気分が動きます。\n- 牡牛座: 現実的な一歩が恋の不安を落ち着かせます。\n- 双子座: いつもと違う角度の言葉が、空気を軽くします。\n- 蟹座: やさしさを受け取る練習の日。遠慮しすぎなくて大丈夫。\n- 獅子座: 勢いはあるけれど、返事は一拍置くと整います。\n- 乙女座: 安心できる場所を先に作ると、会話がやわらぎます。\n- 天秤座: 言葉選びが鍵。軽く見えても本音はちゃんと届きます。\n- 蠍座: 気持ちの揺れを隠しすぎず、やさしく出して大丈夫。\n- 射手座: 魅力が表に出やすい日。見せ方を少しだけ整えて。\n- 山羊座: 細かい確認が信頼につながります。焦らず丁寧に。\n- 水瓶座: 相手とのバランスを見直すと、次の動きが見えます。\n- 魚座: 深読みしすぎたら、事実と想像を分けてみて。\n\n## 今日のルナから\n\nラッキーアクションは「気になっていた予定をひとつ整理する」。今日は派手に運を取りに行くより、心の置き場所を整える日だよ。急がなくて大丈夫。星の流れを味方にして、できることからひとつ選んでいこう。','\n',char(10)),'ja-JP','published','2026-08-19 22:00:24','2026-08-19 22:00:24');
INSERT INTO "blog_engine_articles" ("id","tenant_id","slug","title","body","locale","status","published_at","created_at") VALUES(13,'luna-oracle','square-2','スクエアを悪い配置と決めつけない理由｜ルナのホロスコープ読み',replace('## スクエアを悪い配置と決めつけない理由を読む前に\n\nうん、ここは少し丁寧に見たいところだよ。占いに慣れている人ほど、ひとつの天体だけで結論を急がないはず。ルナはまずネイタルチャート全体を見て、ASC、MC、ハウス、主要アスペクト、そして相談内容に関係する天体を順番に絞ります。\n\n## 見る天体と判断順\n\n基本は太陽、月、水星、金星、火星、木星、土星です。恋愛なら金星と火星だけでなく、月の安心感、水星の言葉、土星の怖さや時間感覚も見ます。相性ではふたりの金星だけでなく、月同士、水星同士、金星と火星、土星が作る距離を重ねます。\n\n## ハウスとアスペクトの扱い\n\nハウスは、悩みがどの生活領域で起きているかを見る場所です。5ハウスならときめき、7ハウスなら一対一の関係、8ハウスなら深い結びつきや不安、12ハウスなら言えない気持ちとして読みます。アスペクトは主要5種を優先し、オーブが狭いもの、相談テーマに直結するもの、ASC/MCに触れるものを重く見ます。\n\n## 相談内容へ戻す\n\nじゃあ、ここがいちばん大事。星の配置は、相談者を縛るためではなく、今どこで苦しくなっているかを見つける地図です。復縁なら未練と愛情を分ける。相性なら良し悪しで切らず、どこで会話がずれるかを見る。片思いなら動く時期より先に、言葉の温度と距離の詰め方を見る。\n\n## よくある誤読\n\n金星が強いから恋愛運が良い、スクエアがあるから相性が悪い、土星があるから終わり、とは読みません。配置は単独で決めつけず、ハウス、支配星、アスペクト、相談内容を重ねます。ヘビーユーザーほど、この重ね方を見ると鑑定の質が分かります。\n\n## ルナの結論\n\n急がなくて大丈夫。スクエアを悪い配置と決めつけない理由は、星の名前を並べるだけでは読み切れません。チャートの構造を見て、そこから気持ちの流れを読み、最後に今の相談へ戻す。この順番を守ることで、占いがただの断定ではなく、次の一歩を選ぶための道具になります。','\n',char(10)),'ja-JP','published','2026-08-20 08:00:24','2026-08-20 04:00:25');
INSERT INTO "blog_engine_articles" ("id","tenant_id","slug","title","body","locale","status","published_at","created_at") VALUES(14,'luna-oracle','todays-fortune-2026-08-21','今日の占い 2026年8月21日｜ルナの星読み',replace('## 今日の星の空気\n\nうん、今日の空気は「小さな約束や習慣が関係を支える日」。月は射手座、金星は山羊座、水星は蟹座の流れとして見ています。細かい度数は簡易計算だから断定に使わず、感情、言葉、惹かれ方の温度を見る目印にします。\n\n## 恋愛と相性の流れ\n\n恋愛では、月の安心感と金星の好みを先に見ます。今日は大きな決断より、相手の返事の速さ、言葉の柔らかさ、自分の心がふっと緩む瞬間を拾うほうが向いています。相性は良い悪いで切らず、会話のリズムと距離感を調整してね。\n\n## 仕事と人間関係\n\n水星の流れを見ると、説明を短く整えるほど伝わりやすい日です。言い切るより、確認を挟むほうが味方が増えます。小さな約束を守る、時間を少し早めに見る、そういう地味な動きが運を支えます。\n\n## 12星座へのひとこと\n\n- 牡羊座: 現実的な一歩が恋の不安を落ち着かせます。\n- 牡牛座: いつもと違う角度の言葉が、空気を軽くします。\n- 双子座: やさしさを受け取る練習の日。遠慮しすぎなくて大丈夫。\n- 蟹座: 勢いはあるけれど、返事は一拍置くと整います。\n- 獅子座: 安心できる場所を先に作ると、会話がやわらぎます。\n- 乙女座: 言葉選びが鍵。軽く見えても本音はちゃんと届きます。\n- 天秤座: 気持ちの揺れを隠しすぎず、やさしく出して大丈夫。\n- 蠍座: 魅力が表に出やすい日。見せ方を少しだけ整えて。\n- 射手座: 細かい確認が信頼につながります。焦らず丁寧に。\n- 山羊座: 相手とのバランスを見直すと、次の動きが見えます。\n- 水瓶座: 深読みしすぎたら、事実と想像を分けてみて。\n- 魚座: 少し外へ意識を向けると、停滞した気分が動きます。\n\n## 今日のルナから\n\nラッキーアクションは「相手のペースを一度尊重する」。今日は派手に運を取りに行くより、心の置き場所を整える日だよ。急がなくて大丈夫。星の流れを味方にして、できることからひとつ選んでいこう。','\n',char(10)),'ja-JP','published','2026-08-20 22:00:24','2026-08-20 22:00:24');
INSERT INTO "blog_engine_articles" ("id","tenant_id","slug","title","body","locale","status","published_at","created_at") VALUES(15,'luna-oracle','fukuen-moon-saturn-2','復縁で月と土星を見る理由｜ルナのホロスコープ読み',replace('## 復縁で月と土星を見る理由を読む前に\n\nうん、ここは少し丁寧に見たいところだよ。占いに慣れている人ほど、ひとつの天体だけで結論を急がないはず。ルナはまずネイタルチャート全体を見て、ASC、MC、ハウス、主要アスペクト、そして相談内容に関係する天体を順番に絞ります。\n\n## 見る天体と判断順\n\n基本は太陽、月、水星、金星、火星、木星、土星です。恋愛なら金星と火星だけでなく、月の安心感、水星の言葉、土星の怖さや時間感覚も見ます。相性ではふたりの金星だけでなく、月同士、水星同士、金星と火星、土星が作る距離を重ねます。\n\n## ハウスとアスペクトの扱い\n\nハウスは、悩みがどの生活領域で起きているかを見る場所です。5ハウスならときめき、7ハウスなら一対一の関係、8ハウスなら深い結びつきや不安、12ハウスなら言えない気持ちとして読みます。アスペクトは主要5種を優先し、オーブが狭いもの、相談テーマに直結するもの、ASC/MCに触れるものを重く見ます。\n\n## 相談内容へ戻す\n\nじゃあ、ここがいちばん大事。星の配置は、相談者を縛るためではなく、今どこで苦しくなっているかを見つける地図です。復縁なら未練と愛情を分ける。相性なら良し悪しで切らず、どこで会話がずれるかを見る。片思いなら動く時期より先に、言葉の温度と距離の詰め方を見る。\n\n## よくある誤読\n\n金星が強いから恋愛運が良い、スクエアがあるから相性が悪い、土星があるから終わり、とは読みません。配置は単独で決めつけず、ハウス、支配星、アスペクト、相談内容を重ねます。ヘビーユーザーほど、この重ね方を見ると鑑定の質が分かります。\n\n## ルナの結論\n\n急がなくて大丈夫。復縁で月と土星を見る理由は、星の名前を並べるだけでは読み切れません。チャートの構造を見て、そこから気持ちの流れを読み、最後に今の相談へ戻す。この順番を守ることで、占いがただの断定ではなく、次の一歩を選ぶための道具になります。','\n',char(10)),'ja-JP','published','2026-08-21 08:00:24','2026-08-21 04:00:25');
INSERT INTO "blog_engine_articles" ("id","tenant_id","slug","title","body","locale","status","published_at","created_at") VALUES(16,'luna-oracle','todays-fortune-2026-08-22','今日の占い 2026年8月22日｜ルナの星読み',replace('## 今日の星の空気\n\nうん、今日の空気は「本音と建前の差を責めずに見分ける日」。月は射手座、金星は山羊座、水星は蟹座の流れとして見ています。細かい度数は簡易計算だから断定に使わず、感情、言葉、惹かれ方の温度を見る目印にします。\n\n## 恋愛と相性の流れ\n\n恋愛では、月の安心感と金星の好みを先に見ます。今日は大きな決断より、相手の返事の速さ、言葉の柔らかさ、自分の心がふっと緩む瞬間を拾うほうが向いています。相性は良い悪いで切らず、会話のリズムと距離感を調整してね。\n\n## 仕事と人間関係\n\n水星の流れを見ると、説明を短く整えるほど伝わりやすい日です。言い切るより、確認を挟むほうが味方が増えます。小さな約束を守る、時間を少し早めに見る、そういう地味な動きが運を支えます。\n\n## 12星座へのひとこと\n\n- 牡羊座: いつもと違う角度の言葉が、空気を軽くします。\n- 牡牛座: やさしさを受け取る練習の日。遠慮しすぎなくて大丈夫。\n- 双子座: 勢いはあるけれど、返事は一拍置くと整います。\n- 蟹座: 安心できる場所を先に作ると、会話がやわらぎます。\n- 獅子座: 言葉選びが鍵。軽く見えても本音はちゃんと届きます。\n- 乙女座: 気持ちの揺れを隠しすぎず、やさしく出して大丈夫。\n- 天秤座: 魅力が表に出やすい日。見せ方を少しだけ整えて。\n- 蠍座: 細かい確認が信頼につながります。焦らず丁寧に。\n- 射手座: 相手とのバランスを見直すと、次の動きが見えます。\n- 山羊座: 深読みしすぎたら、事実と想像を分けてみて。\n- 水瓶座: 少し外へ意識を向けると、停滞した気分が動きます。\n- 魚座: 現実的な一歩が恋の不安を落ち着かせます。\n\n## 今日のルナから\n\nラッキーアクションは「白か淡いピンクを一点だけ入れる」。今日は派手に運を取りに行くより、心の置き場所を整える日だよ。急がなくて大丈夫。星の流れを味方にして、できることからひとつ選んでいこう。','\n',char(10)),'ja-JP','published','2026-08-21 22:00:24','2026-08-21 22:00:24');
INSERT INTO "blog_engine_articles" ("id","tenant_id","slug","title","body","locale","status","published_at","created_at") VALUES(17,'luna-oracle','compatibility-venus-2','相性で金星だけを見ない理由｜ルナのホロスコープ読み',replace('## 相性で金星だけを見ない理由を読む前に\n\nうん、ここは少し丁寧に見たいところだよ。占いに慣れている人ほど、ひとつの天体だけで結論を急がないはず。ルナはまずネイタルチャート全体を見て、ASC、MC、ハウス、主要アスペクト、そして相談内容に関係する天体を順番に絞ります。\n\n## 見る天体と判断順\n\n基本は太陽、月、水星、金星、火星、木星、土星です。恋愛なら金星と火星だけでなく、月の安心感、水星の言葉、土星の怖さや時間感覚も見ます。相性ではふたりの金星だけでなく、月同士、水星同士、金星と火星、土星が作る距離を重ねます。\n\n## ハウスとアスペクトの扱い\n\nハウスは、悩みがどの生活領域で起きているかを見る場所です。5ハウスならときめき、7ハウスなら一対一の関係、8ハウスなら深い結びつきや不安、12ハウスなら言えない気持ちとして読みます。アスペクトは主要5種を優先し、オーブが狭いもの、相談テーマに直結するもの、ASC/MCに触れるものを重く見ます。\n\n## 相談内容へ戻す\n\nじゃあ、ここがいちばん大事。星の配置は、相談者を縛るためではなく、今どこで苦しくなっているかを見つける地図です。復縁なら未練と愛情を分ける。相性なら良し悪しで切らず、どこで会話がずれるかを見る。片思いなら動く時期より先に、言葉の温度と距離の詰め方を見る。\n\n## よくある誤読\n\n金星が強いから恋愛運が良い、スクエアがあるから相性が悪い、土星があるから終わり、とは読みません。配置は単独で決めつけず、ハウス、支配星、アスペクト、相談内容を重ねます。ヘビーユーザーほど、この重ね方を見ると鑑定の質が分かります。\n\n## ルナの結論\n\n急がなくて大丈夫。相性で金星だけを見ない理由は、星の名前を並べるだけでは読み切れません。チャートの構造を見て、そこから気持ちの流れを読み、最後に今の相談へ戻す。この順番を守ることで、占いがただの断定ではなく、次の一歩を選ぶための道具になります。','\n',char(10)),'ja-JP','published','2026-08-22 08:00:53','2026-08-22 04:00:52');
INSERT INTO "blog_engine_articles" ("id","tenant_id","slug","title","body","locale","status","published_at","created_at") VALUES(18,'luna-oracle','todays-fortune-2026-08-23','今日の占い 2026年8月23日｜ルナの星読み',replace('## 今日の星の空気\n\nうん、今日の空気は「好きなものを共有すると距離が縮まりやすい日」。月は山羊座、金星は山羊座、水星は蟹座の流れとして見ています。細かい度数は簡易計算だから断定に使わず、感情、言葉、惹かれ方の温度を見る目印にします。\n\n## 恋愛と相性の流れ\n\n恋愛では、月の安心感と金星の好みを先に見ます。今日は大きな決断より、相手の返事の速さ、言葉の柔らかさ、自分の心がふっと緩む瞬間を拾うほうが向いています。相性は良い悪いで切らず、会話のリズムと距離感を調整してね。\n\n## 仕事と人間関係\n\n水星の流れを見ると、説明を短く整えるほど伝わりやすい日です。言い切るより、確認を挟むほうが味方が増えます。小さな約束を守る、時間を少し早めに見る、そういう地味な動きが運を支えます。\n\n## 12星座へのひとこと\n\n- 牡羊座: やさしさを受け取る練習の日。遠慮しすぎなくて大丈夫。\n- 牡牛座: 勢いはあるけれど、返事は一拍置くと整います。\n- 双子座: 安心できる場所を先に作ると、会話がやわらぎます。\n- 蟹座: 言葉選びが鍵。軽く見えても本音はちゃんと届きます。\n- 獅子座: 気持ちの揺れを隠しすぎず、やさしく出して大丈夫。\n- 乙女座: 魅力が表に出やすい日。見せ方を少しだけ整えて。\n- 天秤座: 細かい確認が信頼につながります。焦らず丁寧に。\n- 蠍座: 相手とのバランスを見直すと、次の動きが見えます。\n- 射手座: 深読みしすぎたら、事実と想像を分けてみて。\n- 山羊座: 少し外へ意識を向けると、停滞した気分が動きます。\n- 水瓶座: 現実的な一歩が恋の不安を落ち着かせます。\n- 魚座: いつもと違う角度の言葉が、空気を軽くします。\n\n## 今日のルナから\n\nラッキーアクションは「朝のうちに水を飲んで深呼吸する」。今日は派手に運を取りに行くより、心の置き場所を整える日だよ。急がなくて大丈夫。星の流れを味方にして、できることからひとつ選んでいこう。','\n',char(10)),'ja-JP','published','2026-08-22 22:00:52','2026-08-22 22:00:52');
INSERT INTO "blog_engine_articles" ("id","tenant_id","slug","title","body","locale","status","published_at","created_at") VALUES(19,'luna-oracle','kataomoi-mercury-mars-2','片思いで水星と火星を見る理由｜ルナのホロスコープ読み',replace('## 片思いで水星と火星を見る理由を読む前に\n\nうん、ここは少し丁寧に見たいところだよ。占いに慣れている人ほど、ひとつの天体だけで結論を急がないはず。ルナはまずネイタルチャート全体を見て、ASC、MC、ハウス、主要アスペクト、そして相談内容に関係する天体を順番に絞ります。\n\n## 見る天体と判断順\n\n基本は太陽、月、水星、金星、火星、木星、土星です。恋愛なら金星と火星だけでなく、月の安心感、水星の言葉、土星の怖さや時間感覚も見ます。相性ではふたりの金星だけでなく、月同士、水星同士、金星と火星、土星が作る距離を重ねます。\n\n## ハウスとアスペクトの扱い\n\nハウスは、悩みがどの生活領域で起きているかを見る場所です。5ハウスならときめき、7ハウスなら一対一の関係、8ハウスなら深い結びつきや不安、12ハウスなら言えない気持ちとして読みます。アスペクトは主要5種を優先し、オーブが狭いもの、相談テーマに直結するもの、ASC/MCに触れるものを重く見ます。\n\n## 相談内容へ戻す\n\nじゃあ、ここがいちばん大事。星の配置は、相談者を縛るためではなく、今どこで苦しくなっているかを見つける地図です。復縁なら未練と愛情を分ける。相性なら良し悪しで切らず、どこで会話がずれるかを見る。片思いなら動く時期より先に、言葉の温度と距離の詰め方を見る。\n\n## よくある誤読\n\n金星が強いから恋愛運が良い、スクエアがあるから相性が悪い、土星があるから終わり、とは読みません。配置は単独で決めつけず、ハウス、支配星、アスペクト、相談内容を重ねます。ヘビーユーザーほど、この重ね方を見ると鑑定の質が分かります。\n\n## ルナの結論\n\n急がなくて大丈夫。片思いで水星と火星を見る理由は、星の名前を並べるだけでは読み切れません。チャートの構造を見て、そこから気持ちの流れを読み、最後に今の相談へ戻す。この順番を守ることで、占いがただの断定ではなく、次の一歩を選ぶための道具になります。','\n',char(10)),'ja-JP','published','2026-08-23 08:00:54','2026-08-23 04:00:54');
INSERT INTO "blog_engine_articles" ("id","tenant_id","slug","title","body","locale","status","published_at","created_at") VALUES(20,'luna-oracle','todays-fortune-2026-08-24','今日の占い 2026年8月24日｜ルナの星読み',replace('## 今日の星の空気\n\nうん、今日の空気は「連絡の温度を少しだけ柔らかくする日」。月は山羊座、金星は山羊座、水星は蟹座の流れとして見ています。細かい度数は簡易計算だから断定に使わず、感情、言葉、惹かれ方の温度を見る目印にします。\n\n## 恋愛と相性の流れ\n\n恋愛では、月の安心感と金星の好みを先に見ます。今日は大きな決断より、相手の返事の速さ、言葉の柔らかさ、自分の心がふっと緩む瞬間を拾うほうが向いています。相性は良い悪いで切らず、会話のリズムと距離感を調整してね。\n\n## 仕事と人間関係\n\n水星の流れを見ると、説明を短く整えるほど伝わりやすい日です。言い切るより、確認を挟むほうが味方が増えます。小さな約束を守る、時間を少し早めに見る、そういう地味な動きが運を支えます。\n\n## 12星座へのひとこと\n\n- 牡羊座: 勢いはあるけれど、返事は一拍置くと整います。\n- 牡牛座: 安心できる場所を先に作ると、会話がやわらぎます。\n- 双子座: 言葉選びが鍵。軽く見えても本音はちゃんと届きます。\n- 蟹座: 気持ちの揺れを隠しすぎず、やさしく出して大丈夫。\n- 獅子座: 魅力が表に出やすい日。見せ方を少しだけ整えて。\n- 乙女座: 細かい確認が信頼につながります。焦らず丁寧に。\n- 天秤座: 相手とのバランスを見直すと、次の動きが見えます。\n- 蠍座: 深読みしすぎたら、事実と想像を分けてみて。\n- 射手座: 少し外へ意識を向けると、停滞した気分が動きます。\n- 山羊座: 現実的な一歩が恋の不安を落ち着かせます。\n- 水瓶座: いつもと違う角度の言葉が、空気を軽くします。\n- 魚座: やさしさを受け取る練習の日。遠慮しすぎなくて大丈夫。\n\n## 今日のルナから\n\nラッキーアクションは「短いメッセージを丁寧に書く」。今日は派手に運を取りに行くより、心の置き場所を整える日だよ。急がなくて大丈夫。星の流れを味方にして、できることからひとつ選んでいこう。','\n',char(10)),'ja-JP','published','2026-08-23 22:00:51','2026-08-23 22:00:51');
INSERT INTO "blog_engine_articles" ("id","tenant_id","slug","title","body","locale","status","published_at","created_at") VALUES(21,'luna-oracle','eighth-house-love-2','8ハウスが恋愛相談で出るとき｜ルナのホロスコープ読み',replace('## 8ハウスが恋愛相談で出るときを読む前に\n\nうん、ここは少し丁寧に見たいところだよ。占いに慣れている人ほど、ひとつの天体だけで結論を急がないはず。ルナはまずネイタルチャート全体を見て、ASC、MC、ハウス、主要アスペクト、そして相談内容に関係する天体を順番に絞ります。\n\n## 見る天体と判断順\n\n基本は太陽、月、水星、金星、火星、木星、土星です。恋愛なら金星と火星だけでなく、月の安心感、水星の言葉、土星の怖さや時間感覚も見ます。相性ではふたりの金星だけでなく、月同士、水星同士、金星と火星、土星が作る距離を重ねます。\n\n## ハウスとアスペクトの扱い\n\nハウスは、悩みがどの生活領域で起きているかを見る場所です。5ハウスならときめき、7ハウスなら一対一の関係、8ハウスなら深い結びつきや不安、12ハウスなら言えない気持ちとして読みます。アスペクトは主要5種を優先し、オーブが狭いもの、相談テーマに直結するもの、ASC/MCに触れるものを重く見ます。\n\n## 相談内容へ戻す\n\nじゃあ、ここがいちばん大事。星の配置は、相談者を縛るためではなく、今どこで苦しくなっているかを見つける地図です。復縁なら未練と愛情を分ける。相性なら良し悪しで切らず、どこで会話がずれるかを見る。片思いなら動く時期より先に、言葉の温度と距離の詰め方を見る。\n\n## よくある誤読\n\n金星が強いから恋愛運が良い、スクエアがあるから相性が悪い、土星があるから終わり、とは読みません。配置は単独で決めつけず、ハウス、支配星、アスペクト、相談内容を重ねます。ヘビーユーザーほど、この重ね方を見ると鑑定の質が分かります。\n\n## ルナの結論\n\n急がなくて大丈夫。8ハウスが恋愛相談で出るときは、星の名前を並べるだけでは読み切れません。チャートの構造を見て、そこから気持ちの流れを読み、最後に今の相談へ戻す。この順番を守ることで、占いがただの断定ではなく、次の一歩を選ぶための道具になります。','\n',char(10)),'ja-JP','published','2026-08-24 08:00:57','2026-08-24 04:00:53');
INSERT INTO "blog_engine_articles" ("id","tenant_id","slug","title","body","locale","status","published_at","created_at") VALUES(22,'luna-oracle','todays-fortune-2026-08-25','今日の占い 2026年8月25日｜ルナの星読み',replace('## 今日の星の空気\n\nうん、今日の空気は「急いで答えを出さず、相手の反応を観察する日」。月は山羊座、金星は山羊座、水星は獅子座の流れとして見ています。細かい度数は簡易計算だから断定に使わず、感情、言葉、惹かれ方の温度を見る目印にします。\n\n## 恋愛と相性の流れ\n\n恋愛では、月の安心感と金星の好みを先に見ます。今日は大きな決断より、相手の返事の速さ、言葉の柔らかさ、自分の心がふっと緩む瞬間を拾うほうが向いています。相性は良い悪いで切らず、会話のリズムと距離感を調整してね。\n\n## 仕事と人間関係\n\n水星の流れを見ると、説明を短く整えるほど伝わりやすい日です。言い切るより、確認を挟むほうが味方が増えます。小さな約束を守る、時間を少し早めに見る、そういう地味な動きが運を支えます。\n\n## 12星座へのひとこと\n\n- 牡羊座: 安心できる場所を先に作ると、会話がやわらぎます。\n- 牡牛座: 言葉選びが鍵。軽く見えても本音はちゃんと届きます。\n- 双子座: 気持ちの揺れを隠しすぎず、やさしく出して大丈夫。\n- 蟹座: 魅力が表に出やすい日。見せ方を少しだけ整えて。\n- 獅子座: 細かい確認が信頼につながります。焦らず丁寧に。\n- 乙女座: 相手とのバランスを見直すと、次の動きが見えます。\n- 天秤座: 深読みしすぎたら、事実と想像を分けてみて。\n- 蠍座: 少し外へ意識を向けると、停滞した気分が動きます。\n- 射手座: 現実的な一歩が恋の不安を落ち着かせます。\n- 山羊座: いつもと違う角度の言葉が、空気を軽くします。\n- 水瓶座: やさしさを受け取る練習の日。遠慮しすぎなくて大丈夫。\n- 魚座: 勢いはあるけれど、返事は一拍置くと整います。\n\n## 今日のルナから\n\nラッキーアクションは「身の回りの香りを変える」。今日は派手に運を取りに行くより、心の置き場所を整える日だよ。急がなくて大丈夫。星の流れを味方にして、できることからひとつ選んでいこう。','\n',char(10)),'ja-JP','published','2026-08-24 22:00:52','2026-08-24 22:00:52');
INSERT INTO "blog_engine_articles" ("id","tenant_id","slug","title","body","locale","status","published_at","created_at") VALUES(23,'luna-oracle','latitude-house-2','高緯度出生地でハウスを補正する理由｜ルナのホロスコープ読み',replace('## 高緯度出生地でハウスを補正する理由を読む前に\n\nうん、ここは少し丁寧に見たいところだよ。占いに慣れている人ほど、ひとつの天体だけで結論を急がないはず。ルナはまずネイタルチャート全体を見て、ASC、MC、ハウス、主要アスペクト、そして相談内容に関係する天体を順番に絞ります。\n\n## 見る天体と判断順\n\n基本は太陽、月、水星、金星、火星、木星、土星です。恋愛なら金星と火星だけでなく、月の安心感、水星の言葉、土星の怖さや時間感覚も見ます。相性ではふたりの金星だけでなく、月同士、水星同士、金星と火星、土星が作る距離を重ねます。\n\n## ハウスとアスペクトの扱い\n\nハウスは、悩みがどの生活領域で起きているかを見る場所です。5ハウスならときめき、7ハウスなら一対一の関係、8ハウスなら深い結びつきや不安、12ハウスなら言えない気持ちとして読みます。アスペクトは主要5種を優先し、オーブが狭いもの、相談テーマに直結するもの、ASC/MCに触れるものを重く見ます。\n\n## 相談内容へ戻す\n\nじゃあ、ここがいちばん大事。星の配置は、相談者を縛るためではなく、今どこで苦しくなっているかを見つける地図です。復縁なら未練と愛情を分ける。相性なら良し悪しで切らず、どこで会話がずれるかを見る。片思いなら動く時期より先に、言葉の温度と距離の詰め方を見る。\n\n## よくある誤読\n\n金星が強いから恋愛運が良い、スクエアがあるから相性が悪い、土星があるから終わり、とは読みません。配置は単独で決めつけず、ハウス、支配星、アスペクト、相談内容を重ねます。ヘビーユーザーほど、この重ね方を見ると鑑定の質が分かります。\n\n## ルナの結論\n\n急がなくて大丈夫。高緯度出生地でハウスを補正する理由は、星の名前を並べるだけでは読み切れません。チャートの構造を見て、そこから気持ちの流れを読み、最後に今の相談へ戻す。この順番を守ることで、占いがただの断定ではなく、次の一歩を選ぶための道具になります。','\n',char(10)),'ja-JP','published','2026-08-25 08:00:52','2026-08-25 04:00:52');
INSERT INTO "blog_engine_articles" ("id","tenant_id","slug","title","body","locale","status","published_at","created_at") VALUES(24,'luna-oracle','todays-fortune-2026-08-26','今日の占い 2026年8月26日｜ルナの星読み',replace('## 今日の星の空気\n\nうん、今日の空気は「気持ちを整えてから言葉を選ぶ日」。月は水瓶座、金星は山羊座、水星は獅子座の流れとして見ています。細かい度数は簡易計算だから断定に使わず、感情、言葉、惹かれ方の温度を見る目印にします。\n\n## 恋愛と相性の流れ\n\n恋愛では、月の安心感と金星の好みを先に見ます。今日は大きな決断より、相手の返事の速さ、言葉の柔らかさ、自分の心がふっと緩む瞬間を拾うほうが向いています。相性は良い悪いで切らず、会話のリズムと距離感を調整してね。\n\n## 仕事と人間関係\n\n水星の流れを見ると、説明を短く整えるほど伝わりやすい日です。言い切るより、確認を挟むほうが味方が増えます。小さな約束を守る、時間を少し早めに見る、そういう地味な動きが運を支えます。\n\n## 12星座へのひとこと\n\n- 牡羊座: 言葉選びが鍵。軽く見えても本音はちゃんと届きます。\n- 牡牛座: 気持ちの揺れを隠しすぎず、やさしく出して大丈夫。\n- 双子座: 魅力が表に出やすい日。見せ方を少しだけ整えて。\n- 蟹座: 細かい確認が信頼につながります。焦らず丁寧に。\n- 獅子座: 相手とのバランスを見直すと、次の動きが見えます。\n- 乙女座: 深読みしすぎたら、事実と想像を分けてみて。\n- 天秤座: 少し外へ意識を向けると、停滞した気分が動きます。\n- 蠍座: 現実的な一歩が恋の不安を落ち着かせます。\n- 射手座: いつもと違う角度の言葉が、空気を軽くします。\n- 山羊座: やさしさを受け取る練習の日。遠慮しすぎなくて大丈夫。\n- 水瓶座: 勢いはあるけれど、返事は一拍置くと整います。\n- 魚座: 安心できる場所を先に作ると、会話がやわらぎます。\n\n## 今日のルナから\n\nラッキーアクションは「気になっていた予定をひとつ整理する」。今日は派手に運を取りに行くより、心の置き場所を整える日だよ。急がなくて大丈夫。星の流れを味方にして、できることからひとつ選んでいこう。','\n',char(10)),'ja-JP','published','2026-08-25 22:00:50','2026-08-25 22:00:50');
INSERT INTO "blog_engine_articles" ("id","tenant_id","slug","title","body","locale","status","published_at","created_at") VALUES(25,'luna-oracle','asc-mc-love-2','ASCとMCを恋愛相談へ戻す読み方｜ルナのホロスコープ読み',replace('## ASCとMCを恋愛相談へ戻す読み方を読む前に\n\nうん、ここは少し丁寧に見たいところだよ。占いに慣れている人ほど、ひとつの天体だけで結論を急がないはず。ルナはまずネイタルチャート全体を見て、ASC、MC、ハウス、主要アスペクト、そして相談内容に関係する天体を順番に絞ります。\n\n## 見る天体と判断順\n\n基本は太陽、月、水星、金星、火星、木星、土星です。恋愛なら金星と火星だけでなく、月の安心感、水星の言葉、土星の怖さや時間感覚も見ます。相性ではふたりの金星だけでなく、月同士、水星同士、金星と火星、土星が作る距離を重ねます。\n\n## ハウスとアスペクトの扱い\n\nハウスは、悩みがどの生活領域で起きているかを見る場所です。5ハウスならときめき、7ハウスなら一対一の関係、8ハウスなら深い結びつきや不安、12ハウスなら言えない気持ちとして読みます。アスペクトは主要5種を優先し、オーブが狭いもの、相談テーマに直結するもの、ASC/MCに触れるものを重く見ます。\n\n## 相談内容へ戻す\n\nじゃあ、ここがいちばん大事。星の配置は、相談者を縛るためではなく、今どこで苦しくなっているかを見つける地図です。復縁なら未練と愛情を分ける。相性なら良し悪しで切らず、どこで会話がずれるかを見る。片思いなら動く時期より先に、言葉の温度と距離の詰め方を見る。\n\n## よくある誤読\n\n金星が強いから恋愛運が良い、スクエアがあるから相性が悪い、土星があるから終わり、とは読みません。配置は単独で決めつけず、ハウス、支配星、アスペクト、相談内容を重ねます。ヘビーユーザーほど、この重ね方を見ると鑑定の質が分かります。\n\n## ルナの結論\n\n急がなくて大丈夫。ASCとMCを恋愛相談へ戻す読み方は、星の名前を並べるだけでは読み切れません。チャートの構造を見て、そこから気持ちの流れを読み、最後に今の相談へ戻す。この順番を守ることで、占いがただの断定ではなく、次の一歩を選ぶための道具になります。','\n',char(10)),'ja-JP','published','2026-08-26 08:00:50','2026-08-26 04:00:52');
CREATE TABLE sns_posts (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  tenant_id TEXT NOT NULL,
  provider TEXT,
  external_post_id TEXT,
  status TEXT NOT NULL DEFAULT 'draft',
  locale TEXT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (tenant_id) REFERENCES studioos_tenant_metadata(tenant_id)
);
CREATE TABLE reel_assets (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  tenant_id TEXT NOT NULL,
  storage_namespace TEXT NOT NULL,
  public_url TEXT,
  status TEXT NOT NULL DEFAULT 'draft',
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (tenant_id) REFERENCES studioos_tenant_metadata(tenant_id)
);
CREATE TABLE growth_metric_points (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  tenant_id TEXT NOT NULL,
  metric_name TEXT NOT NULL,
  metric_value REAL,
  observed_at TEXT,
  source TEXT,
  FOREIGN KEY (tenant_id) REFERENCES studioos_tenant_metadata(tenant_id)
);
CREATE TABLE growth_evidence_sources (
  source_id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  source_type TEXT NOT NULL,
  provider TEXT,
  source_name TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'active',
  retrieved_at TEXT,
  observed_at TEXT,
  quality_score REAL,
  FOREIGN KEY (tenant_id) REFERENCES studioos_tenant_metadata(tenant_id)
);
CREATE TABLE growth_evidence_claims (
  claim_id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  source_id TEXT NOT NULL,
  evidence_scope TEXT NOT NULL,
  statement TEXT NOT NULL,
  metric_name TEXT,
  metric_value REAL,
  confidence REAL,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (tenant_id) REFERENCES studioos_tenant_metadata(tenant_id),
  FOREIGN KEY (source_id) REFERENCES growth_evidence_sources(source_id)
);
CREATE TABLE growth_hypotheses (
  hypothesis_id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  observation TEXT NOT NULL,
  hypothesis TEXT NOT NULL,
  confidence REAL,
  status TEXT NOT NULL DEFAULT 'draft',
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (tenant_id) REFERENCES studioos_tenant_metadata(tenant_id)
);
CREATE TABLE growth_proposals (
  proposal_id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  hypothesis_id TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'review_required',
  risk_class TEXT NOT NULL,
  execution_allowed INTEGER NOT NULL DEFAULT 0 CHECK (execution_allowed = 0),
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (tenant_id) REFERENCES studioos_tenant_metadata(tenant_id),
  FOREIGN KEY (hypothesis_id) REFERENCES growth_hypotheses(hypothesis_id)
);
CREATE TABLE growth_experiments (
  experiment_id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  proposal_id TEXT,
  status TEXT NOT NULL DEFAULT 'DRAFT',
  requires_start_approval INTEGER NOT NULL DEFAULT 1 CHECK (requires_start_approval = 1),
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (tenant_id) REFERENCES studioos_tenant_metadata(tenant_id)
);
CREATE TABLE growth_knowledge_items (
  knowledge_id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'draft',
  learning TEXT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (tenant_id) REFERENCES studioos_tenant_metadata(tenant_id)
);
CREATE TABLE growth_memory (
  memory_id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  proposal_id TEXT,
  experiment_id TEXT,
  predicted_value REAL,
  actual_value REAL,
  absolute_error REAL,
  relative_error REAL,
  reusable INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (tenant_id) REFERENCES studioos_tenant_metadata(tenant_id)
);
CREATE TABLE growth_precision_snapshots (
  snapshot_id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  sample_size INTEGER NOT NULL DEFAULT 0,
  calibration_status TEXT NOT NULL DEFAULT 'insufficient_learning',
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (tenant_id) REFERENCES studioos_tenant_metadata(tenant_id)
);
CREATE TABLE studioos_reading_feedback (import_id INTEGER PRIMARY KEY AUTOINCREMENT, source_id TEXT NOT NULL, source_tenant_id TEXT NOT NULL, tenant_id TEXT NOT NULL, character_id TEXT NOT NULL, theme TEXT, rating INTEGER, comment TEXT, page_path TEXT, created_at TEXT, UNIQUE(source_id, source_tenant_id));
INSERT INTO "studioos_reading_feedback" ("import_id","source_id","source_tenant_id","tenant_id","character_id","theme","rating","comment","page_path","created_at") VALUES(1,'915d7424-994d-44c0-9cdf-b083dbb08deb','luna-starwind','luna-oracle','luna','verification','helpful','','/ai-reading','2026-08-15 14:44:32');
CREATE TABLE studioos_import_ledger (source_table TEXT NOT NULL, source_id TEXT NOT NULL, source_tenant_id TEXT NOT NULL, target_table TEXT NOT NULL, target_id TEXT, target_tenant_id TEXT NOT NULL, status TEXT NOT NULL, PRIMARY KEY(source_table, source_id, source_tenant_id));
INSERT INTO "studioos_import_ledger" ("source_table","source_id","source_tenant_id","target_table","target_id","target_tenant_id","status") VALUES('analytics_events','e8564ce0-3d62-4259-a97f-0b3b6c607add','luna-starwind','analytics_events','deterministic:analytics:e8564ce0-3d62-4259-a97f-0b3b6c607add','luna-oracle','imported');
INSERT INTO "studioos_import_ledger" ("source_table","source_id","source_tenant_id","target_table","target_id","target_tenant_id","status") VALUES('analytics_events','a56bc8e5-d565-4e3a-8d89-ebee6f801e0d','luna-starwind','analytics_events','deterministic:analytics:a56bc8e5-d565-4e3a-8d89-ebee6f801e0d','luna-oracle','imported');
INSERT INTO "studioos_import_ledger" ("source_table","source_id","source_tenant_id","target_table","target_id","target_tenant_id","status") VALUES('analytics_events','5434220c-07cb-4caf-bfad-62121fc15c49','luna-starwind','analytics_events','deterministic:analytics:5434220c-07cb-4caf-bfad-62121fc15c49','luna-oracle','imported');
INSERT INTO "studioos_import_ledger" ("source_table","source_id","source_tenant_id","target_table","target_id","target_tenant_id","status") VALUES('analytics_events','14805c38-6d07-4f78-9ea8-076e265c2d48','luna-starwind','analytics_events','deterministic:analytics:14805c38-6d07-4f78-9ea8-076e265c2d48','luna-oracle','imported');
INSERT INTO "studioos_import_ledger" ("source_table","source_id","source_tenant_id","target_table","target_id","target_tenant_id","status") VALUES('analytics_events','2e3ef99e-0aa9-421a-b7be-cf31fcdb9e82','luna-starwind','analytics_events','deterministic:analytics:2e3ef99e-0aa9-421a-b7be-cf31fcdb9e82','luna-oracle','imported');
INSERT INTO "studioos_import_ledger" ("source_table","source_id","source_tenant_id","target_table","target_id","target_tenant_id","status") VALUES('analytics_events','bc14bd53-ed56-4b75-94df-e3c596912e85','luna-starwind','analytics_events','deterministic:analytics:bc14bd53-ed56-4b75-94df-e3c596912e85','luna-oracle','imported');
INSERT INTO "studioos_import_ledger" ("source_table","source_id","source_tenant_id","target_table","target_id","target_tenant_id","status") VALUES('analytics_events','adccde02-4271-451c-b79e-925339c2ca07','luna-starwind','analytics_events','deterministic:analytics:adccde02-4271-451c-b79e-925339c2ca07','luna-oracle','imported');
INSERT INTO "studioos_import_ledger" ("source_table","source_id","source_tenant_id","target_table","target_id","target_tenant_id","status") VALUES('analytics_events','66e060b8-8e0b-4ec7-8f9c-5b6791c09318','luna-starwind','analytics_events','deterministic:analytics:66e060b8-8e0b-4ec7-8f9c-5b6791c09318','luna-oracle','imported');
INSERT INTO "studioos_import_ledger" ("source_table","source_id","source_tenant_id","target_table","target_id","target_tenant_id","status") VALUES('analytics_events','e8e3a55e-75be-481c-b0e7-0275c0c9aff2','luna-starwind','analytics_events','deterministic:analytics:e8e3a55e-75be-481c-b0e7-0275c0c9aff2','luna-oracle','imported');
INSERT INTO "studioos_import_ledger" ("source_table","source_id","source_tenant_id","target_table","target_id","target_tenant_id","status") VALUES('analytics_events','22bf8f2d-81ad-4224-ac20-6f067c71fa79','luna-starwind','analytics_events','deterministic:analytics:22bf8f2d-81ad-4224-ac20-6f067c71fa79','luna-oracle','imported');
INSERT INTO "studioos_import_ledger" ("source_table","source_id","source_tenant_id","target_table","target_id","target_tenant_id","status") VALUES('analytics_events','e898cacf-5eda-458f-b8f1-7eea89a67388','luna-starwind','analytics_events','deterministic:analytics:e898cacf-5eda-458f-b8f1-7eea89a67388','luna-oracle','imported');
INSERT INTO "studioos_import_ledger" ("source_table","source_id","source_tenant_id","target_table","target_id","target_tenant_id","status") VALUES('analytics_events','137c4564-52dc-4e36-a6ef-5030b9b8237e','luna-starwind','analytics_events','deterministic:analytics:137c4564-52dc-4e36-a6ef-5030b9b8237e','luna-oracle','imported');
INSERT INTO "studioos_import_ledger" ("source_table","source_id","source_tenant_id","target_table","target_id","target_tenant_id","status") VALUES('analytics_events','d44fba55-3199-44cb-bce1-6c8594418185','luna-starwind','analytics_events','deterministic:analytics:d44fba55-3199-44cb-bce1-6c8594418185','luna-oracle','imported');
INSERT INTO "studioos_import_ledger" ("source_table","source_id","source_tenant_id","target_table","target_id","target_tenant_id","status") VALUES('analytics_events','512750e9-1658-4f1f-8fd3-44f0e16695cb','luna-starwind','analytics_events','deterministic:analytics:512750e9-1658-4f1f-8fd3-44f0e16695cb','luna-oracle','imported');
INSERT INTO "studioos_import_ledger" ("source_table","source_id","source_tenant_id","target_table","target_id","target_tenant_id","status") VALUES('analytics_events','c8dc47f1-979f-415a-a357-61761ddfb28f','luna-starwind','analytics_events','deterministic:analytics:c8dc47f1-979f-415a-a357-61761ddfb28f','luna-oracle','imported');
INSERT INTO "studioos_import_ledger" ("source_table","source_id","source_tenant_id","target_table","target_id","target_tenant_id","status") VALUES('analytics_events','76aff599-44d3-4456-9906-f5fecf86098e','luna-starwind','analytics_events','deterministic:analytics:76aff599-44d3-4456-9906-f5fecf86098e','luna-oracle','imported');
INSERT INTO "studioos_import_ledger" ("source_table","source_id","source_tenant_id","target_table","target_id","target_tenant_id","status") VALUES('analytics_events','5242f272-ef01-4a16-a59f-69d61301db34','luna-starwind','analytics_events','deterministic:analytics:5242f272-ef01-4a16-a59f-69d61301db34','luna-oracle','imported');
INSERT INTO "studioos_import_ledger" ("source_table","source_id","source_tenant_id","target_table","target_id","target_tenant_id","status") VALUES('analytics_events','dc1e3056-410f-4c47-963a-0b3f43cd5016','luna-starwind','analytics_events','deterministic:analytics:dc1e3056-410f-4c47-963a-0b3f43cd5016','luna-oracle','imported');
INSERT INTO "studioos_import_ledger" ("source_table","source_id","source_tenant_id","target_table","target_id","target_tenant_id","status") VALUES('analytics_events','646704f5-151d-4601-ac42-455ecc09259f','luna-starwind','analytics_events','deterministic:analytics:646704f5-151d-4601-ac42-455ecc09259f','luna-oracle','imported');
INSERT INTO "studioos_import_ledger" ("source_table","source_id","source_tenant_id","target_table","target_id","target_tenant_id","status") VALUES('analytics_events','9b9deee7-c067-4767-851e-7ce64624c3d9','luna-starwind','analytics_events','deterministic:analytics:9b9deee7-c067-4767-851e-7ce64624c3d9','luna-oracle','imported');
INSERT INTO "studioos_import_ledger" ("source_table","source_id","source_tenant_id","target_table","target_id","target_tenant_id","status") VALUES('reading_feedback','915d7424-994d-44c0-9cdf-b083dbb08deb','luna-starwind','studioos_reading_feedback','deterministic:feedback:915d7424-994d-44c0-9cdf-b083dbb08deb','luna-oracle','imported');
INSERT INTO "studioos_import_ledger" ("source_table","source_id","source_tenant_id","target_table","target_id","target_tenant_id","status") VALUES('blog_engine_settings','unknown','luna-starwind','blog_engine_settings','deterministic:settings:unknown','luna-oracle','imported');
INSERT INTO "studioos_import_ledger" ("source_table","source_id","source_tenant_id","target_table","target_id","target_tenant_id","status") VALUES('blog_engine_articles','538a11a7-7560-40e4-ad5f-ed7c5611c3e8','luna-starwind','blog_engine_articles','deterministic:article:538a11a7-7560-40e4-ad5f-ed7c5611c3e8','luna-oracle','imported');
INSERT INTO "studioos_import_ledger" ("source_table","source_id","source_tenant_id","target_table","target_id","target_tenant_id","status") VALUES('blog_engine_articles','67b50240-849b-47bd-9797-7b93af2c5636','luna-starwind','blog_engine_articles','deterministic:article:67b50240-849b-47bd-9797-7b93af2c5636','luna-oracle','imported');
INSERT INTO "studioos_import_ledger" ("source_table","source_id","source_tenant_id","target_table","target_id","target_tenant_id","status") VALUES('blog_engine_articles','9d529fc8-0101-4bbd-b66f-e58feac3ce18','luna-starwind','blog_engine_articles','deterministic:article:9d529fc8-0101-4bbd-b66f-e58feac3ce18','luna-oracle','imported');
INSERT INTO "studioos_import_ledger" ("source_table","source_id","source_tenant_id","target_table","target_id","target_tenant_id","status") VALUES('blog_engine_articles','c8b7f76c-bfd1-4a78-a631-7c5d4609b7b8','luna-starwind','blog_engine_articles','deterministic:article:c8b7f76c-bfd1-4a78-a631-7c5d4609b7b8','luna-oracle','imported');
INSERT INTO "studioos_import_ledger" ("source_table","source_id","source_tenant_id","target_table","target_id","target_tenant_id","status") VALUES('blog_engine_articles','7e709e89-0869-40d2-bdc9-f2d0886a759b','luna-starwind','blog_engine_articles','deterministic:article:7e709e89-0869-40d2-bdc9-f2d0886a759b','luna-oracle','imported');
INSERT INTO "studioos_import_ledger" ("source_table","source_id","source_tenant_id","target_table","target_id","target_tenant_id","status") VALUES('blog_engine_articles','28e16c92-404d-47f7-92d0-f339cacc7c9b','luna-starwind','blog_engine_articles','deterministic:article:28e16c92-404d-47f7-92d0-f339cacc7c9b','luna-oracle','imported');
INSERT INTO "studioos_import_ledger" ("source_table","source_id","source_tenant_id","target_table","target_id","target_tenant_id","status") VALUES('blog_engine_articles','58b89cd6-cd83-498e-b47c-e61d2bbb1475','luna-starwind','blog_engine_articles','deterministic:article:58b89cd6-cd83-498e-b47c-e61d2bbb1475','luna-oracle','imported');
INSERT INTO "studioos_import_ledger" ("source_table","source_id","source_tenant_id","target_table","target_id","target_tenant_id","status") VALUES('blog_engine_articles','19a0f524-4009-4606-8b09-7bbc5f1c5320','luna-starwind','blog_engine_articles','deterministic:article:19a0f524-4009-4606-8b09-7bbc5f1c5320','luna-oracle','imported');
INSERT INTO "studioos_import_ledger" ("source_table","source_id","source_tenant_id","target_table","target_id","target_tenant_id","status") VALUES('blog_engine_articles','dbdbaa24-aaa9-45b4-94cd-1e221636a6ba','luna-starwind','blog_engine_articles','deterministic:article:dbdbaa24-aaa9-45b4-94cd-1e221636a6ba','luna-oracle','imported');
INSERT INTO "studioos_import_ledger" ("source_table","source_id","source_tenant_id","target_table","target_id","target_tenant_id","status") VALUES('blog_engine_articles','88e690e1-277b-4ec9-b259-6588dcada725','luna-starwind','blog_engine_articles','deterministic:article:88e690e1-277b-4ec9-b259-6588dcada725','luna-oracle','imported');
INSERT INTO "studioos_import_ledger" ("source_table","source_id","source_tenant_id","target_table","target_id","target_tenant_id","status") VALUES('blog_engine_articles','ce0cb02c-3f60-47ae-8893-42007b068438','luna-starwind','blog_engine_articles','deterministic:article:ce0cb02c-3f60-47ae-8893-42007b068438','luna-oracle','imported');
INSERT INTO "studioos_import_ledger" ("source_table","source_id","source_tenant_id","target_table","target_id","target_tenant_id","status") VALUES('blog_engine_articles','b6d43766-f16f-48ff-8f44-e502d20ae8c9','luna-starwind','blog_engine_articles','deterministic:article:b6d43766-f16f-48ff-8f44-e502d20ae8c9','luna-oracle','imported');
INSERT INTO "studioos_import_ledger" ("source_table","source_id","source_tenant_id","target_table","target_id","target_tenant_id","status") VALUES('blog_engine_articles','346a0ffb-1856-43ea-81da-1e108c22c1d1','luna-starwind','blog_engine_articles','deterministic:article:346a0ffb-1856-43ea-81da-1e108c22c1d1','luna-oracle','imported');
INSERT INTO "studioos_import_ledger" ("source_table","source_id","source_tenant_id","target_table","target_id","target_tenant_id","status") VALUES('blog_engine_articles','d5df176a-4fb1-4e55-90e1-70e4cd4aeaab','luna-starwind','blog_engine_articles','deterministic:article:d5df176a-4fb1-4e55-90e1-70e4cd4aeaab','luna-oracle','imported');
INSERT INTO "studioos_import_ledger" ("source_table","source_id","source_tenant_id","target_table","target_id","target_tenant_id","status") VALUES('blog_engine_articles','b96fe7f4-f542-408f-9b0b-4a67d5e7ffec','luna-starwind','blog_engine_articles','deterministic:article:b96fe7f4-f542-408f-9b0b-4a67d5e7ffec','luna-oracle','imported');
INSERT INTO "studioos_import_ledger" ("source_table","source_id","source_tenant_id","target_table","target_id","target_tenant_id","status") VALUES('blog_engine_articles','282ce05e-2c2d-4abd-b3b9-aaf3f3c87bd8','luna-starwind','blog_engine_articles','deterministic:article:282ce05e-2c2d-4abd-b3b9-aaf3f3c87bd8','luna-oracle','imported');
INSERT INTO "studioos_import_ledger" ("source_table","source_id","source_tenant_id","target_table","target_id","target_tenant_id","status") VALUES('blog_engine_articles','56b8c8b6-9d77-4952-9261-72e16bfa96f3','luna-starwind','blog_engine_articles','deterministic:article:56b8c8b6-9d77-4952-9261-72e16bfa96f3','luna-oracle','imported');
INSERT INTO "studioos_import_ledger" ("source_table","source_id","source_tenant_id","target_table","target_id","target_tenant_id","status") VALUES('blog_engine_articles','9919c068-7355-4f24-b7ca-c8f967407b28','luna-starwind','blog_engine_articles','deterministic:article:9919c068-7355-4f24-b7ca-c8f967407b28','luna-oracle','imported');
INSERT INTO "studioos_import_ledger" ("source_table","source_id","source_tenant_id","target_table","target_id","target_tenant_id","status") VALUES('blog_engine_articles','1af211e2-61ab-42e1-bb7e-a607ba02546e','luna-starwind','blog_engine_articles','deterministic:article:1af211e2-61ab-42e1-bb7e-a607ba02546e','luna-oracle','imported');
INSERT INTO "studioos_import_ledger" ("source_table","source_id","source_tenant_id","target_table","target_id","target_tenant_id","status") VALUES('blog_engine_articles','79fd8d91-9865-4d5d-b089-8f55abbccf8c','luna-starwind','blog_engine_articles','deterministic:article:79fd8d91-9865-4d5d-b089-8f55abbccf8c','luna-oracle','imported');
INSERT INTO "studioos_import_ledger" ("source_table","source_id","source_tenant_id","target_table","target_id","target_tenant_id","status") VALUES('blog_engine_articles','9cf533e8-bac6-4bcc-9798-ea513024438a','luna-starwind','blog_engine_articles','deterministic:article:9cf533e8-bac6-4bcc-9798-ea513024438a','luna-oracle','imported');
INSERT INTO "studioos_import_ledger" ("source_table","source_id","source_tenant_id","target_table","target_id","target_tenant_id","status") VALUES('blog_engine_articles','3e9d13a3-4c3c-4736-8dc6-75fb424c6911','luna-starwind','blog_engine_articles','deterministic:article:3e9d13a3-4c3c-4736-8dc6-75fb424c6911','luna-oracle','imported');
INSERT INTO "studioos_import_ledger" ("source_table","source_id","source_tenant_id","target_table","target_id","target_tenant_id","status") VALUES('blog_engine_articles','404e4011-df90-4d39-83f1-c80abeba0303','luna-starwind','blog_engine_articles','deterministic:article:404e4011-df90-4d39-83f1-c80abeba0303','luna-oracle','imported');
INSERT INTO "studioos_import_ledger" ("source_table","source_id","source_tenant_id","target_table","target_id","target_tenant_id","status") VALUES('blog_engine_articles','b2135725-6ec5-4d82-a74d-8b28c8e7d1d8','luna-starwind','blog_engine_articles','deterministic:article:b2135725-6ec5-4d82-a74d-8b28c8e7d1d8','luna-oracle','imported');
INSERT INTO "studioos_import_ledger" ("source_table","source_id","source_tenant_id","target_table","target_id","target_tenant_id","status") VALUES('blog_engine_articles','b67a6bd3-f3a5-4bce-ad49-67a7b23942f4','luna-starwind','blog_engine_articles','deterministic:article:b67a6bd3-f3a5-4bce-ad49-67a7b23942f4','luna-oracle','status_sync_published');
INSERT INTO "studioos_import_ledger" ("source_table","source_id","source_tenant_id","target_table","target_id","target_tenant_id","status") VALUES('analytics_events','f05632ea-2986-4730-8201-33e0fb264fe2','luna-starwind','analytics_events','deterministic:analytics:f05632ea-2986-4730-8201-33e0fb264fe2','luna-oracle','phase5_delta_imported');
INSERT INTO "studioos_import_ledger" ("source_table","source_id","source_tenant_id","target_table","target_id","target_tenant_id","status") VALUES('analytics_events','6877eb2f-2602-45af-8843-cb5ce2732d44','luna-starwind','analytics_events','deterministic:analytics:6877eb2f-2602-45af-8843-cb5ce2732d44','luna-oracle','phase5_delta_imported');
INSERT INTO "studioos_import_ledger" ("source_table","source_id","source_tenant_id","target_table","target_id","target_tenant_id","status") VALUES('analytics_events','1798d412-a072-45a6-86ef-6a15a1aca9fb','luna-starwind','analytics_events','deterministic:analytics:1798d412-a072-45a6-86ef-6a15a1aca9fb','luna-oracle','phase5_delta_imported');
INSERT INTO "studioos_import_ledger" ("source_table","source_id","source_tenant_id","target_table","target_id","target_tenant_id","status") VALUES('analytics_events','057da7fc-2ea2-49d5-b181-ef5f81261e58','luna-starwind','analytics_events','deterministic:analytics:057da7fc-2ea2-49d5-b181-ef5f81261e58','luna-oracle','phase5_delta_imported');
INSERT INTO "studioos_import_ledger" ("source_table","source_id","source_tenant_id","target_table","target_id","target_tenant_id","status") VALUES('analytics_events','dbe5cf93-c6a5-41c9-9615-03de28fdd896','luna-starwind','analytics_events','deterministic:analytics:dbe5cf93-c6a5-41c9-9615-03de28fdd896','luna-oracle','phase5_delta_imported');
INSERT INTO "studioos_import_ledger" ("source_table","source_id","source_tenant_id","target_table","target_id","target_tenant_id","status") VALUES('analytics_events','6e2bd356-78b0-4c4e-8374-8c19824eb56e','luna-starwind','analytics_events','deterministic:analytics:6e2bd356-78b0-4c4e-8374-8c19824eb56e','luna-oracle','phase5_delta_imported');
INSERT INTO "studioos_import_ledger" ("source_table","source_id","source_tenant_id","target_table","target_id","target_tenant_id","status") VALUES('analytics_events','2a3c8435-785b-4982-a70e-5363c039771b','luna-starwind','analytics_events','deterministic:analytics:2a3c8435-785b-4982-a70e-5363c039771b','luna-oracle','phase5_delta_imported');
INSERT INTO "studioos_import_ledger" ("source_table","source_id","source_tenant_id","target_table","target_id","target_tenant_id","status") VALUES('analytics_events','0a0e30c8-71d0-434a-b0f4-c1769ef153d6','luna-starwind','analytics_events','deterministic:analytics:0a0e30c8-71d0-434a-b0f4-c1769ef153d6','luna-oracle','phase5_delta_imported');
INSERT INTO "studioos_import_ledger" ("source_table","source_id","source_tenant_id","target_table","target_id","target_tenant_id","status") VALUES('analytics_events','ad4c23f0-6009-49fb-bdd6-a1b8975856ff','luna-starwind','analytics_events','deterministic:analytics:ad4c23f0-6009-49fb-bdd6-a1b8975856ff','luna-oracle','phase5_delta_imported');
INSERT INTO "studioos_import_ledger" ("source_table","source_id","source_tenant_id","target_table","target_id","target_tenant_id","status") VALUES('analytics_events','6bf43e9f-43bc-4a1f-84ca-5b458a7906ab','luna-starwind','analytics_events','deterministic:analytics:6bf43e9f-43bc-4a1f-84ca-5b458a7906ab','luna-oracle','phase5_delta_imported');
INSERT INTO "studioos_import_ledger" ("source_table","source_id","source_tenant_id","target_table","target_id","target_tenant_id","status") VALUES('analytics_events','ac16ece0-90b3-425f-8aaa-2bfb94fcd537','luna-starwind','analytics_events','deterministic:analytics:ac16ece0-90b3-425f-8aaa-2bfb94fcd537','luna-oracle','phase5_delta_imported');
INSERT INTO "studioos_import_ledger" ("source_table","source_id","source_tenant_id","target_table","target_id","target_tenant_id","status") VALUES('analytics_events','d18a0894-aa4f-4e04-9672-b23764c3ae64','luna-starwind','analytics_events','deterministic:analytics:d18a0894-aa4f-4e04-9672-b23764c3ae64','luna-oracle','phase5_delta_imported');
INSERT INTO "studioos_import_ledger" ("source_table","source_id","source_tenant_id","target_table","target_id","target_tenant_id","status") VALUES('analytics_events','e7f97aa4-7110-4316-8d29-614d8274f934','luna-starwind','analytics_events','deterministic:analytics:e7f97aa4-7110-4316-8d29-614d8274f934','luna-oracle','phase5_delta_imported');
DELETE FROM sqlite_sequence;
INSERT INTO "sqlite_sequence" ("name","seq") VALUES('analytics_events',33);
INSERT INTO "sqlite_sequence" ("name","seq") VALUES('studioos_reading_feedback',1);
INSERT INTO "sqlite_sequence" ("name","seq") VALUES('blog_engine_settings',1);
INSERT INTO "sqlite_sequence" ("name","seq") VALUES('blog_engine_articles',25);
CREATE INDEX idx_studioos_tenant_guild ON studioos_tenant_metadata(guild_id);
CREATE INDEX idx_studioos_tenant_market ON studioos_tenant_metadata(market, locale);
CREATE INDEX idx_studioos_member_tenant ON studioos_member_context(tenant_id, member_id);
CREATE INDEX idx_analytics_events_tenant_time ON analytics_events(tenant_id, created_at);
CREATE INDEX idx_blog_articles_tenant_status ON blog_engine_articles(tenant_id, status);
CREATE INDEX idx_sns_posts_tenant_status ON sns_posts(tenant_id, status);
CREATE INDEX idx_reel_assets_tenant_status ON reel_assets(tenant_id, status);
CREATE INDEX idx_growth_source_tenant ON growth_evidence_sources(tenant_id, status);
CREATE INDEX idx_growth_claim_tenant ON growth_evidence_claims(tenant_id, evidence_scope);
CREATE INDEX idx_growth_hypothesis_tenant ON growth_hypotheses(tenant_id, status);
CREATE INDEX idx_growth_proposal_tenant ON growth_proposals(tenant_id, status);
